export enum CombatSkill {
  BASIC_ATTACK = 'BASIC_ATTACK',
  BATTLE_SKILL = 'BATTLE_SKILL',
  COMBO_SKILL  = 'COMBO_SKILL',
  ULTIMATE     = 'ULTIMATE',
}

export enum Attribute {
  STRENGTH  = 'STRENGTH',
  AGILITY   = 'AGILITY',
  INTELLECT = 'INTELLECT',
  WILL      = 'WILL',
}

export enum MainStat {
  MAX_HP      = 'MAX_HP',
  BASE_ATTACK = 'BASE_ATTACK',
  DEFENSE     = 'DEFENSE',
}

export enum CombatResource {
  SKILL_POINT     = 'SKILL_POINT',
  ULTIMATE_ENERGY = 'ULTIMATE_ENERGY',
}

export enum PhysicalStatus {
  LIFT       = 'LIFT',
  KNOCK_DOWN = 'KNOCK_DOWN',
  CRUSH      = 'CRUSH',
  BREACH     = 'BREACH',
}

export enum Element {
  PHYSICAL = 'PHYSICAL',
  HEAT     = 'HEAT',
  CRYO     = 'CRYO',
  NATURE   = 'NATURE',
  ELECTRIC = 'ELECTRIC',
}

export enum ArtsReaction {
  COMBUSTION     = 'COMBUSTION',
  SOLIDIFICATION = 'SOLIDIFICATION',
  CORROSION      = 'CORROSION',
  ELECTRIFICATION = 'ELECTRIFICATION',
}

/** Elemental inflictions that can be applied to a target, plus the universal VULNERABLE debuff. */
export enum Infliction {
  HEAT_INFLICTION     = 'HEAT_INFLICTION',
  CRYO_INFLICTION     = 'CRYO_INFLICTION',
  NATURE_INFLICTION   = 'NATURE_INFLICTION',
  ELECTRIC_INFLICTION = 'ELECTRIC_INFLICTION',
  VULNERABLE          = 'VULNERABLE',
}

/** Subset of Infliction — the four elemental inflictions that trigger ArtsReactions. */
export enum ArtsInfliction {
  HEAT_INFLICTION     = 'HEAT_INFLICTION',
  CRYO_INFLICTION     = 'CRYO_INFLICTION',
  NATURE_INFLICTION   = 'NATURE_INFLICTION',
  ELECTRIC_INFLICTION = 'ELECTRIC_INFLICTION',
}

export enum OperatorClass {
  GUARD     = 'GUARD',
  CASTER    = 'CASTER',
  STRIKER   = 'STRIKER',
  VANGUARD  = 'VANGUARD',
  DEFENDER  = 'DEFENDER',
  SUPPORTER = 'SUPPORTER',
}

export enum WeaponType {
  SWORD       = 'SWORD',
  GREAT_SWORD = 'GREAT_SWORD',
  POLEARM     = 'POLEARM',
  HANDCANNON  = 'HANDCANNON',
  ARTS_UNIT   = 'ARTS_UNIT',
}

export enum GearType {
  ARMOR  = 'ARMOR',
  GLOVES = 'GLOVES',
  KIT    = 'KIT',
}

export enum WeaponSkill {
  // ── Stat boosts (each has _S / _M / _L size variants) ──────────────────────
  ATTACK_BOOST_S                  = 'ATTACK_BOOST_S',
  ATTACK_BOOST_M                  = 'ATTACK_BOOST_M',
  ATTACK_BOOST_L                  = 'ATTACK_BOOST_L',

  STRENGTH_BOOST_S                = 'STRENGTH_BOOST_S',
  STRENGTH_BOOST_M                = 'STRENGTH_BOOST_M',
  STRENGTH_BOOST_L                = 'STRENGTH_BOOST_L',

  AGILITY_BOOST_S                 = 'AGILITY_BOOST_S',
  AGILITY_BOOST_M                 = 'AGILITY_BOOST_M',
  AGILITY_BOOST_L                 = 'AGILITY_BOOST_L',

  INTELLECT_BOOST_S               = 'INTELLECT_BOOST_S',
  INTELLECT_BOOST_M               = 'INTELLECT_BOOST_M',
  INTELLECT_BOOST_L               = 'INTELLECT_BOOST_L',

  WILL_BOOST_S                    = 'WILL_BOOST_S',
  WILL_BOOST_M                    = 'WILL_BOOST_M',
  WILL_BOOST_L                    = 'WILL_BOOST_L',

  MAIN_ATTRIBUTE_BOOST_S          = 'MAIN_ATTRIBUTE_BOOST_S',
  MAIN_ATTRIBUTE_BOOST_M          = 'MAIN_ATTRIBUTE_BOOST_M',
  MAIN_ATTRIBUTE_BOOST_L          = 'MAIN_ATTRIBUTE_BOOST_L',

  PHYSICAL_DAMAGE_BOOST_S         = 'PHYSICAL_DAMAGE_BOOST_S',
  PHYSICAL_DAMAGE_BOOST_M         = 'PHYSICAL_DAMAGE_BOOST_M',
  PHYSICAL_DAMAGE_BOOST_L         = 'PHYSICAL_DAMAGE_BOOST_L',

  HEAT_DAMAGE_BOOST_S             = 'HEAT_DAMAGE_BOOST_S',
  HEAT_DAMAGE_BOOST_M             = 'HEAT_DAMAGE_BOOST_M',
  HEAT_DAMAGE_BOOST_L             = 'HEAT_DAMAGE_BOOST_L',

  CRYO_DAMAGE_BOOST_S             = 'CRYO_DAMAGE_BOOST_S',
  CRYO_DAMAGE_BOOST_M             = 'CRYO_DAMAGE_BOOST_M',
  CRYO_DAMAGE_BOOST_L             = 'CRYO_DAMAGE_BOOST_L',

  NATURE_DAMAGE_BOOST_S           = 'NATURE_DAMAGE_BOOST_S',
  NATURE_DAMAGE_BOOST_M           = 'NATURE_DAMAGE_BOOST_M',
  NATURE_DAMAGE_BOOST_L           = 'NATURE_DAMAGE_BOOST_L',

  ELECTRIC_DAMAGE_BOOST_S         = 'ELECTRIC_DAMAGE_BOOST_S',
  ELECTRIC_DAMAGE_BOOST_M         = 'ELECTRIC_DAMAGE_BOOST_M',
  ELECTRIC_DAMAGE_BOOST_L         = 'ELECTRIC_DAMAGE_BOOST_L',

  ULTIMATE_GAIN_EFFICIENCY_BOOST_S = 'ULTIMATE_GAIN_EFFICIENCY_BOOST_S',
  ULTIMATE_GAIN_EFFICIENCY_BOOST_M = 'ULTIMATE_GAIN_EFFICIENCY_BOOST_M',
  ULTIMATE_GAIN_EFFICIENCY_BOOST_L = 'ULTIMATE_GAIN_EFFICIENCY_BOOST_L',

  HP_BOOST_S                      = 'HP_BOOST_S',
  HP_BOOST_M                      = 'HP_BOOST_M',
  HP_BOOST_L                      = 'HP_BOOST_L',

  ARTS_BOOST_S                    = 'ARTS_BOOST_S',
  ARTS_BOOST_M                    = 'ARTS_BOOST_M',
  ARTS_BOOST_L                    = 'ARTS_BOOST_L',

  ARTS_INTENSITY_BOOST_S          = 'ARTS_INTENSITY_BOOST_S',
  ARTS_INTENSITY_BOOST_M          = 'ARTS_INTENSITY_BOOST_M',
  ARTS_INTENSITY_BOOST_L          = 'ARTS_INTENSITY_BOOST_L',

  CRITICAL_RATE_BOOST_S           = 'CRITICAL_RATE_BOOST_S',
  CRITICAL_RATE_BOOST_M           = 'CRITICAL_RATE_BOOST_M',
  CRITICAL_RATE_BOOST_L           = 'CRITICAL_RATE_BOOST_L',

  // ── Named weapon skills ─────────────────────────────────────────────────────
  BRUTALITY_DISCIPLINARIAN        = 'BRUTALITY_DISCIPLINARIAN',
  TWILIGHT_BLAZING_WAIL           = 'TWILIGHT_BLAZING_WAIL',
  TWILIGHT_AZURE_CLOUDS           = 'TWILIGHT_AZURE_CLOUDS',
  INFLICTION_WHITE_NIGHT_NOVA     = 'INFLICTION_WHITE_NIGHT_NOVA',
  FLOW_REINCARNATION              = 'FLOW_REINCARNATION',
  INFLICTION_LONG_TIME_WISH       = 'INFLICTION_LONG_TIME_WISH',
  FLOW_THERMAL_RELEASE            = 'FLOW_THERMAL_RELEASE',
  INFLICTION_COVETOUS_BUILDUP     = 'INFLICTION_COVETOUS_BUILDUP',
  COMBATIVE_ANTHEM_OF_CINDER      = 'COMBATIVE_ANTHEM_OF_CINDER',
  INSPIRING_BACK_TO_THE_BROKEN_CITY = 'INSPIRING_BACK_TO_THE_BROKEN_CITY',
  TWILIGHT_IMPOSING_PEAK          = 'TWILIGHT_IMPOSING_PEAK',
  FLOW_UNBRIDLED_EDGE             = 'FLOW_UNBRIDLED_EDGE',
  INFLICTION_SINCERE_INTERROGATION = 'INFLICTION_SINCERE_INTERROGATION',
  SUPPRESSION_FIN_CHASERS_INTENT  = 'SUPPRESSION_FIN_CHASERS_INTENT',
  PURSUIT_UNENDING_CYCLE          = 'PURSUIT_UNENDING_CYCLE',
  SUPPRESSION_EMERGENCY_BOOST     = 'SUPPRESSION_EMERGENCY_BOOST',
  ASSAULT_ARMAMENT_PREP           = 'ASSAULT_ARMAMENT_PREP',
}
