export enum CombatSkillType {
  BASIC_ATTACK = "BASIC_ATTACK",
  BATTLE_SKILL = "BATTLE_SKILL",
  COMBO_SKILL = "COMBO_SKILL",
  ULTIMATE = "ULTIMATE",
}

export enum MainStatType {
  BASE_HP = "BASE_HP",
  HP_FROM_STRENGTH = "HP_FROM_STRENGTH",
  BASE_ATTACK = "BASE_ATTACK",
  ATTACK_BONUS = "ATTACK_BONUS",
  BASE_DEFENSE = "BASE_DEFENSE",
}

export enum CombatResourceType {
  HP = "HP",
  SKILL_POINT = "SKILL_POINT",
  ULTIMATE_ENERGY = "ULTIMATE_ENERGY",
  STAGGER = "STAGGER",
  COOLDOWN = "COOLDOWN",
}

export enum VerbType {
  APPLY = "APPLY",
  CONSUME = "CONSUME",
  RECOVER = "RECOVER",
  RETURN = "RETURN",
}

export enum EventComponentType {
  EVENT = "EVENT",
  SEGMENT = "SEGMENT",
  FRAME = "FRAME",
}

export enum DataSourceType {
  END_AXIS = "END_AXIS",
  WARFARIN = "WARFARIN",
  SELF = "SELF",
}

export enum DurationUnit {
  FRAME = "FRAME",
  SECOND = "SECOND",
}

export enum EventFrameType {
  NORMAL = "NORMAL",
  FINAL_STRIKE = "FINAL_STRIKE",
  FINISHER = "FINISHER",
  DIVE = "DIVE",
  DAMAGE_OVER_TIME = "DAMAGE_OVER_TIME",
  GUARANTEED_HIT = "GUARANTEED_HIT",
  PASSIVE = "PASSIVE",
  INTERRUPTIBLE = "INTERRUPTIBLE",
}

export enum EventStatusType {
  EXPIRED = "EXPIRED",
  CONSUMED = "CONSUMED",
  REFRESHED = "REFRESHED",
  TRIGGERED = "TRIGGERED",
  EXTENDED = "EXTENDED",
}

export enum RequirementStateType {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  APPLIED = "APPLIED",
  CONSUMED = "CONSUMED",
  EQ = "EQ",
  GT = "GT",
  GEQ = "GEQ",
  LT = "LT",
  LEQ = "LEQ",
}

export enum ComparisonType {
  EQ = "EQ",
  GT = "GT",
  GEQ = "GEQ",
  LT = "LT",
  LEQ = "LEQ",
}

export enum StackInteractionType {
  NONE = "NONE",
  REFRESH = "REFRESH",
  EXTEND = "EXTEND",
  MERGE = "MERGE",
  APPLY = "APPLY",
  CONSUME = "CONSUME",
}

export enum ElementType {
  NONE = "NONE",
  PHYSICAL = "PHYSICAL",
  HEAT = "HEAT",
  CRYO = "CRYO",
  NATURE = "NATURE",
  ELECTRIC = "ELECTRIC",
}

/** Maps status types to their associated element (for coloring). */
export const STATUS_ELEMENT: Record<string, string> = {
  MELTING_FLAME:    ElementType.HEAT,
  SCORCHING_HEART_EFFECT: ElementType.HEAT,
  COMBUSTION:       ElementType.HEAT,
  SOLIDIFICATION:   ElementType.CRYO,
  CRIT_STACKS:      ElementType.CRYO,
  CORROSION:        ElementType.NATURE,
  ELECTRIFICATION:  ElementType.ELECTRIC,
  THUNDERLANCE:     ElementType.ELECTRIC,
};

export const ELEMENT_LABELS: Record<ElementType, string> = {
  [ElementType.NONE]:     'None',
  [ElementType.PHYSICAL]: 'Physical',
  [ElementType.HEAT]:     'Heat',
  [ElementType.CRYO]:     'Cryo',
  [ElementType.NATURE]:   'Nature',
  [ElementType.ELECTRIC]: 'Electric',
};

export const ELEMENT_COLORS: Record<ElementType, string> = {
  [ElementType.NONE]:     '#cccccc',
  [ElementType.PHYSICAL]: '#b0b8c0',
  [ElementType.HEAT]:     '#e85535',
  [ElementType.CRYO]:     '#55ccee',
  [ElementType.NATURE]:   '#55cc55',
  [ElementType.ELECTRIC]: '#e8c840',
};

export enum StatusType {
  // ── Arts reactions (also in REACTION_STATUS_TYPES — not pure statuses) ─────
  COMBUSTION = "COMBUSTION",
  SOLIDIFICATION = "SOLIDIFICATION",
  CORROSION = "CORROSION",
  ELECTRIFICATION = "ELECTRIFICATION",
  // ── Operator buffs ─────────────────────────────────────────────────────────
  MELTING_FLAME = "MELTING_FLAME",
  THUNDERLANCE = "THUNDERLANCE",
  CRIT_STACKS = "CRIT_STACKS",
  SQUAD_BUFF = "SQUAD_BUFF",
  SCORCHING_FANGS = "SCORCHING_FANGS",
  // ── Gear set effects ──────────────────────────────────────────────────────
  GEAR_BUFF = "GEAR_BUFF",
  // ── Team statuses ─────────────────────────────────────────────────────────
  LINK = "LINK",
  ARTS_AMP = "ARTS_AMP",
  SHIELD = "SHIELD",
  UNBRIDLED_EDGE = "UNBRIDLED_EDGE",
  WILDLAND_TREKKER = "WILDLAND_TREKKER",
  MESSENGERS_SONG = "MESSENGERS_SONG",
  // ── Operator talents ──────────────────────────────────────────────────────
  SCORCHING_HEART = "SCORCHING_HEART",
  SCORCHING_HEART_EFFECT = "SCORCHING_HEART_EFFECT",
  // ── Enemy debuffs ─────────────────────────────────────────────────────────
  FOCUS = "FOCUS",
  SUSCEPTIBILITY = "SUSCEPTIBILITY",
  FRAGILITY = "FRAGILITY",
  ORIGINIUM_CRYSTAL = "ORIGINIUM_CRYSTAL",
  WEAKEN = "WEAKEN",
  DMG_REDUCTION = "DMG_REDUCTION",
  PROTECTION = "PROTECTION",
  // ── Physical statuses ───────────────────────────────────────────────────────
  LIFT = "LIFT",
  KNOCK_DOWN = "KNOCK_DOWN",
  CRUSH = "CRUSH",
  BREACH = "BREACH",
  // ── Potential buffs ───────────────────────────────────────────────────────
  LAEVATAIN_POTENTIAL5_PROOF_OF_EXISTENCE = "LAEVATAIN_POTENTIAL5_PROOF_OF_EXISTENCE",
  AKEKURI_POTENTIAL1_POSITIVE_FEEDBACK = "AKEKURI_POTENTIAL1_POSITIVE_FEEDBACK",
  AKEKURI_POTENTIAL5_TEMPO_OF_AWARENESS = "AKEKURI_POTENTIAL5_TEMPO_OF_AWARENESS",
  ARDELIA_POTENTIAL5_VOLCANIC_STEAM = "ARDELIA_POTENTIAL5_VOLCANIC_STEAM",
  ENDMINISTRATOR_POTENTIAL1_FINAL_AWAKENING = "ENDMINISTRATOR_POTENTIAL1_FINAL_AWAKENING",
  ENDMINISTRATOR_POTENTIAL2_REFLECTION_OF_AUTHORITY = "ENDMINISTRATOR_POTENTIAL2_REFLECTION_OF_AUTHORITY",
  ENDMINISTRATOR_POTENTIAL5 = "ENDMINISTRATOR_POTENTIAL5",
  CHEN_QIANYU_POTENTIAL1_SHADOWLESS = "CHEN_QIANYU_POTENTIAL1_SHADOWLESS",
  GILBERTA_POTENTIAL5_SPECIAL_MAIL = "GILBERTA_POTENTIAL5_SPECIAL_MAIL",
  LIFENG_POTENTIAL5_UNREMITTING = "LIFENG_POTENTIAL5_UNREMITTING",
  EMBER_POTENTIAL5_THE_STEEL_OATH = "EMBER_POTENTIAL5_THE_STEEL_OATH",
  PERLICA_POTENTIAL3_SUPERVISORY_DUTIES = "PERLICA_POTENTIAL3_SUPERVISORY_DUTIES",
  ARCLIGHT_POTENTIAL5_SERVANT_OF_THE_WILDLANDS = "ARCLIGHT_POTENTIAL5_SERVANT_OF_THE_WILDLANDS",
  ESTELLA_POTENTIAL5_SURVIVAL_IS_A_WIN = "ESTELLA_POTENTIAL5_SURVIVAL_IS_A_WIN",
  CATCHER_POTENTIAL1_MULTI_LAYERED_READINESS = "CATCHER_POTENTIAL1_MULTI_LAYERED_READINESS",
  FLUORITE_POTENTIAL5_CRAVER_OF_CHAOS = "FLUORITE_POTENTIAL5_CRAVER_OF_CHAOS",
  LAST_RITE_POTENTIAL5_WINTER_IS_RETURNING = "LAST_RITE_POTENTIAL5_WINTER_IS_RETURNING",
  YVONNE_POTENTIAL5_EXPERT_MECHCRAFTER = "YVONNE_POTENTIAL5_EXPERT_MECHCRAFTER",
  POGRANICHNIK_POTENTIAL5_NEWLY_FORGED_BLADE = "POGRANICHNIK_POTENTIAL5_NEWLY_FORGED_BLADE",
}

/** Damage formula multiplier factor that a status contributes to. */
export enum DamageFactorType {
  NONE = "NONE",
  MULTIPLIER_GROUP = "MULTIPLIER_GROUP",
  AMP = "AMP",
  STAGGER = "STAGGER",
  LINK = "LINK",
  WEAKEN = "WEAKEN",
  SUSCEPTIBILITY = "SUSCEPTIBILITY",
  FRAGILITY = "FRAGILITY",
  DMG_REDUCTION = "DMG_REDUCTION",
  PROTECTION = "PROTECTION",
  DEFENSE = "DEFENSE",
  RESISTANCE = "RESISTANCE",
}

/** Maps known StatusTypes to the damage formula factor they contribute to. Unknown types default to NONE. */
export const STATUS_DAMAGE_FACTOR: Partial<Record<string, DamageFactorType>> = {
  // Arts reactions — deal damage, don't directly map to a single multiplier factor
  [StatusType.COMBUSTION]: DamageFactorType.NONE,
  [StatusType.SOLIDIFICATION]: DamageFactorType.NONE,
  [StatusType.CORROSION]: DamageFactorType.RESISTANCE,
  [StatusType.ELECTRIFICATION]: DamageFactorType.FRAGILITY,
  // Operator buffs
  [StatusType.MELTING_FLAME]: DamageFactorType.NONE,
  [StatusType.THUNDERLANCE]: DamageFactorType.NONE,
  [StatusType.CRIT_STACKS]: DamageFactorType.NONE,
  [StatusType.SQUAD_BUFF]: DamageFactorType.MULTIPLIER_GROUP,
  [StatusType.SCORCHING_FANGS]: DamageFactorType.RESISTANCE,
  // Gear set effects
  [StatusType.GEAR_BUFF]: DamageFactorType.NONE,
  // Team statuses
  [StatusType.LINK]: DamageFactorType.LINK,
  [StatusType.ARTS_AMP]: DamageFactorType.AMP,
  [StatusType.SHIELD]: DamageFactorType.NONE,
  [StatusType.UNBRIDLED_EDGE]: DamageFactorType.MULTIPLIER_GROUP,
  [StatusType.WILDLAND_TREKKER]: DamageFactorType.MULTIPLIER_GROUP,
  [StatusType.SCORCHING_HEART]: DamageFactorType.NONE,
  [StatusType.SCORCHING_HEART_EFFECT]: DamageFactorType.RESISTANCE,
  // Enemy debuffs
  [StatusType.FOCUS]: DamageFactorType.SUSCEPTIBILITY,
  [StatusType.SUSCEPTIBILITY]: DamageFactorType.SUSCEPTIBILITY,
  [StatusType.FRAGILITY]: DamageFactorType.FRAGILITY,
  [StatusType.ORIGINIUM_CRYSTAL]: DamageFactorType.FRAGILITY,
  [StatusType.WEAKEN]: DamageFactorType.WEAKEN,
  [StatusType.DMG_REDUCTION]: DamageFactorType.DMG_REDUCTION,
  [StatusType.PROTECTION]: DamageFactorType.PROTECTION,
  // Physical statuses
  [StatusType.LIFT]: DamageFactorType.STAGGER,
  [StatusType.KNOCK_DOWN]: DamageFactorType.STAGGER,
  [StatusType.CRUSH]: DamageFactorType.NONE,
  [StatusType.BREACH]: DamageFactorType.FRAGILITY,
  // Team passives
  [StatusType.MESSENGERS_SONG]: DamageFactorType.NONE,
  // Potential buffs
  [StatusType.LAEVATAIN_POTENTIAL5_PROOF_OF_EXISTENCE]: DamageFactorType.NONE,
  [StatusType.AKEKURI_POTENTIAL1_POSITIVE_FEEDBACK]: DamageFactorType.NONE,
  [StatusType.AKEKURI_POTENTIAL5_TEMPO_OF_AWARENESS]: DamageFactorType.NONE,
  [StatusType.ARDELIA_POTENTIAL5_VOLCANIC_STEAM]: DamageFactorType.NONE,
  [StatusType.ENDMINISTRATOR_POTENTIAL1_FINAL_AWAKENING]: DamageFactorType.NONE,
  [StatusType.ENDMINISTRATOR_POTENTIAL2_REFLECTION_OF_AUTHORITY]: DamageFactorType.NONE,
  [StatusType.ENDMINISTRATOR_POTENTIAL5]: DamageFactorType.NONE,
  [StatusType.CHEN_QIANYU_POTENTIAL1_SHADOWLESS]: DamageFactorType.NONE,
  [StatusType.GILBERTA_POTENTIAL5_SPECIAL_MAIL]: DamageFactorType.NONE,
  [StatusType.LIFENG_POTENTIAL5_UNREMITTING]: DamageFactorType.NONE,
  [StatusType.EMBER_POTENTIAL5_THE_STEEL_OATH]: DamageFactorType.NONE,
  [StatusType.PERLICA_POTENTIAL3_SUPERVISORY_DUTIES]: DamageFactorType.NONE,
  [StatusType.ARCLIGHT_POTENTIAL5_SERVANT_OF_THE_WILDLANDS]: DamageFactorType.NONE,
  [StatusType.ESTELLA_POTENTIAL5_SURVIVAL_IS_A_WIN]: DamageFactorType.NONE,
  [StatusType.CATCHER_POTENTIAL1_MULTI_LAYERED_READINESS]: DamageFactorType.NONE,
  [StatusType.FLUORITE_POTENTIAL5_CRAVER_OF_CHAOS]: DamageFactorType.NONE,
  [StatusType.LAST_RITE_POTENTIAL5_WINTER_IS_RETURNING]: DamageFactorType.NONE,
  [StatusType.YVONNE_POTENTIAL5_EXPERT_MECHCRAFTER]: DamageFactorType.NONE,
  [StatusType.POGRANICHNIK_POTENTIAL5_NEWLY_FORGED_BLADE]: DamageFactorType.NONE,
};

/** Arts inflictions — elemental inflictions that trigger arts reactions. */
export enum ArtsInflictionType {
  HEAT_INFLICTION = "HEAT_INFLICTION",
  CRYO_INFLICTION = "CRYO_INFLICTION",
  NATURE_INFLICTION = "NATURE_INFLICTION",
  ELECTRIC_INFLICTION = "ELECTRIC_INFLICTION",
}

/** Physical inflictions. */
export enum PhysicalInflictionType {
  VULNERABLE = "VULNERABLE",
}

/** All infliction types = arts + physical. */
export type InflictionType = ArtsInflictionType | PhysicalInflictionType;
// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InflictionType = { ...ArtsInflictionType, ...PhysicalInflictionType } as typeof ArtsInflictionType & typeof PhysicalInflictionType;

/** Arts reactions — triggered by arts infliction combinations. */
export enum ArtsReactionType {
  COMBUSTION = "COMBUSTION",
  SOLIDIFICATION = "SOLIDIFICATION",
  CORROSION = "CORROSION",
  ELECTRIFICATION = "ELECTRIFICATION",
}

/** Physical statuses — triggered by physical reactions (stagger consumption). */
export enum PhysicalStatusType {
  LIFT = "LIFT",
  KNOCK_DOWN = "KNOCK_DOWN",
  BREACH = "BREACH",
  CRUSH = "CRUSH",
  SHATTER = "SHATTER",
}

/** All built-in reaction types = arts reactions + physical statuses. */
export type ReactionType = ArtsReactionType | PhysicalStatusType;
// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReactionType = { ...ArtsReactionType, ...PhysicalStatusType } as typeof ArtsReactionType & typeof PhysicalStatusType;

export { OperatorClassType } from '../model/enums/operators';

export enum WeaponType {
  SWORD = "SWORD",
  GREAT_SWORD = "GREAT_SWORD",
  POLEARM = "POLEARM",
  HANDCANNON = "HANDCANNON",
  ARTS_UNIT = "ARTS_UNIT",
}

export enum GearCategory {
  ARMOR = "ARMOR",
  GLOVES = "GLOVES",
  KIT = "KIT",
}

export enum BasicAttackType {
  BATK = "BATK",
  FINISHER = "FINISHER",
  DIVE = "DIVE",
}

/** Categorization of BATK sequences — NORMAL hits and FINAL_ATTACK (last hit in chain). */
export enum BatkType {
  NORMAL = "NORMAL",
  FINAL_ATTACK = "FINAL_ATTACK",
}

export enum GearSetType {
  NONE = "NONE",
  AIC_HEAVY = "AIC_HEAVY",
  AIC_LIGHT = "AIC_LIGHT",
  ARMORED_MSGR = "ARMORED_MSGR",
  ROVING_MSGR = "ROVING_MSGR",
  MORDVOLT_INSULATION = "MORDVOLT_INSULATION",
  MORDVOLT_RESISTANT = "MORDVOLT_RESISTANT",
  ABURREY_LEGACY = "ABURREY_LEGACY",
  CATASTROPHE = "CATASTROPHE",
  SWORDMANCER = "SWORDMANCER",
  LYNX = "LYNX",
  AETHERTECH = "AETHERTECH",
  BONEKRUSHA = "BONEKRUSHA",
  PULSER_LABS = "PULSER_LABS",
  FRONTIERS = "FRONTIERS",
  HOT_WORK = "HOT_WORK",
  MI_SECURITY = "MI_SECURITY",
  TYPE_50_YINGLUNG = "TYPE_50_YINGLUNG",
  TIDE_SURGE = "TIDE_SURGE",
  ETERNAL_XIRANITE = "ETERNAL_XIRANITE",
}

export enum GearSetEffectType {
  HOT_WORK = "HOT_WORK",
  PULSER_LABS = "PULSER_LABS",
  AETHERTECH = "AETHERTECH",
  SWORDMANCER = "SWORDMANCER",
  MI_SECURITY = "MI_SECURITY",
  FRONTIERS = "FRONTIERS",
  TYPE_50_YINGLUNG = "TYPE_50_YINGLUNG",
  LYNX = "LYNX",
  ETERNAL_XIRANITE = "ETERNAL_XIRANITE",
  BONEKRUSHA = "BONEKRUSHA",
  CATASTROPHE = "CATASTROPHE",
  ABURREY_LEGACY = "ABURREY_LEGACY",
  ARMORED_MSGR = "ARMORED_MSGR",
  ROVING_MSGR = "ROVING_MSGR",
  MORDVOLT_INSULATION = "MORDVOLT_INSULATION",
  MORDVOLT_RESISTANT = "MORDVOLT_RESISTANT",
  AIC_HEAVY = "AIC_HEAVY",
  AIC_LIGHT = "AIC_LIGHT",
  TIDE_SURGE = "TIDE_SURGE",
}

export enum EventType {
  COMBAT_SKILL = "COMBAT_SKILL",
  STATUS = "STATUS",
}

export enum EventOriginType {
  OPERATOR = "OPERATOR",
  GEAR_EFFECT = "GEAR_EFFECT",
  WEAPON = "WEAPON",
  CONSUMABLE = "CONSUMABLE",
  ENEMY = "ENEMY",
}

/** Time manipulation effects that prevent other events from starting. */
export enum TimeInteractionType {
  /** No interaction with other timelines — purely cosmetic/tracking. */
  NONE = "NONE",
  /** No other events can start on any timeline while this is active. */
  TIME_STOP = "TIME_STOP",
  /** Delays all other timelines by this event's duration (e.g. dash with dodge). */
  TIME_DELAY = "TIME_DELAY",
}

/** Whether an event segment's duration is tied to game-time (affected by time-stops) or real-time (unaffected). */
export enum TimeDependency {
  GAME_TIME = "GAME_TIME",
  REAL_TIME = "REAL_TIME",
}

/** Enhancement tier of a skill variant. Base skills are NORMAL; absence implies NORMAL. */
export enum EnhancementType {
  NORMAL = "NORMAL",
  ENHANCED = "ENHANCED",
  EMPOWERED = "EMPOWERED",
}

/** The phase type of an event segment. */
export enum SegmentType {
  ANIMATION = "ANIMATION",
  STASIS = "STASIS",
  NORMAL = "NORMAL",
  ACTIVE = "ACTIVE",
  COOLDOWN = "COOLDOWN",
  INPUT_DELAY = "INPUT_DELAY",
}

export enum TimelineSourceType {
  OPERATOR = "OPERATOR",
  GEAR_EFFECT = "GEAR_EFFECT",
  WEAPON = "WEAPON",
  ENEMY = "ENEMY",
  COMMON = "COMMON",
  TACTICAL = "TACTICAL",
  FREEFORM = "FREEFORM",
}

export enum InteractionModeType {
  STRICT = "STRICT",
  FREEFORM = "FREEFORM",
  DEBUG = "DEBUG",
}

export enum TargetType {
  ENEMY = "ENEMY",
  SELF = "SELF",
  TEAM = "TEAM",
  TEAM_MEMBER = "TEAM_MEMBER",
  OTHER_OPERATORS = "OTHER_OPERATORS",
}

export { StatType, StatOwnerType, STAT_ATTRIBUTION, getStatsForTarget } from '../model/enums/stats';
export { GearType } from '../model/enums/gears';

export enum CombatSkillsType {
  // Common
  DASH = "DASH",
  FINISHER = "FINISHER",
  DIVE = "DIVE",

  // Laevatain
  FLAMING_CINDERS = "FLAMING_CINDERS",
  FLAMING_CINDERS_ENHANCED = "FLAMING_CINDERS_ENHANCED",
  SMOULDERING_FIRE = "SMOULDERING_FIRE",
  SMOULDERING_FIRE_ENHANCED = "SMOULDERING_FIRE_ENHANCED",
  SMOULDERING_FIRE_EMPOWERED = "SMOULDERING_FIRE_EMPOWERED",
  SMOULDERING_FIRE_ENHANCED_EMPOWERED = "SMOULDERING_FIRE_ENHANCED_EMPOWERED",
  SEETHE = "SEETHE",
  TWILIGHT = "TWILIGHT",
  // Antal
  EXCHANGE_CURRENT = "EXCHANGE_CURRENT",
  SPECIFIED_RESEARCH_SUBJECT = "SPECIFIED_RESEARCH_SUBJECT",
  EMP_TEST_SITE = "EMP_TEST_SITE",
  OVERCLOCKED_MOMENT = "OVERCLOCKED_MOMENT",
  // Akekuri
  SWORD_OF_ASPIRATION = "SWORD_OF_ASPIRATION",
  BURST_OF_PASSION = "BURST_OF_PASSION",
  FLASH_AND_DASH = "FLASH_AND_DASH",
  SQUAD_ON_ME = "SQUAD_ON_ME",
  // Wulfgard
  RAPID_FIRE_AKIMBO = "RAPID_FIRE_AKIMBO",
  THERMITE_TRACERS = "THERMITE_TRACERS",
  FRAG_GRENADE_BETA = "FRAG_GRENADE_BETA",
  WOLVEN_FURY = "WOLVEN_FURY",
  // Ardelia
  ROCKY_WHISPERS = "ROCKY_WHISPERS",
  DOLLY_RUSH = "DOLLY_RUSH",
  ERUPTION_COLUMN = "ERUPTION_COLUMN",
  WOOLY_PARTY = "WOOLY_PARTY",
  // Endministrator
  DESTRUCTIVE_SEQUENCE = "DESTRUCTIVE_SEQUENCE",
  CONSTRUCTIVE_SEQUENCE = "CONSTRUCTIVE_SEQUENCE",
  SEALING_SEQUENCE = "SEALING_SEQUENCE",
  BOMBARDMENT_SEQUENCE = "BOMBARDMENT_SEQUENCE",
  // Lifeng
  RUINATION = "RUINATION",
  TURBID_AVATAR = "TURBID_AVATAR",
  ASPECT_OF_WRATH = "ASPECT_OF_WRATH",
  HEART_OF_THE_UNMOVING = "HEART_OF_THE_UNMOVING",
  // Chen Qianyu
  SOARING_BREAK = "SOARING_BREAK",
  ASCENDING_STRIKE = "ASCENDING_STRIKE",
  SOAR_TO_THE_STARS = "SOAR_TO_THE_STARS",
  BLADE_GALE = "BLADE_GALE",
  // Estella
  AUDIO_NOISE = "AUDIO_NOISE",
  ONOMATOPOEIA = "ONOMATOPOEIA",
  DISTORTION = "DISTORTION",
  TREMOLO = "TREMOLO",
  // Ember
  SWORD_ART_OF_ASSAULT = "SWORD_ART_OF_ASSAULT",
  FORWARD_MARCH = "FORWARD_MARCH",
  FRONTLINE_SUPPORT = "FRONTLINE_SUPPORT",
  RE_IGNITED_OATH = "RE_IGNITED_OATH",
  // Snowshine
  HYPOTHERMIC_ASSAULT = "HYPOTHERMIC_ASSAULT",
  SATURATED_DEFENSE = "SATURATED_DEFENSE",
  POLAR_RESCUE = "POLAR_RESCUE",
  FRIGID_SNOWFIELD = "FRIGID_SNOWFIELD",
  // Catcher
  RIGID_INTERDICTION_BASIC = "RIGID_INTERDICTION_BASIC",
  RIGID_INTERDICTION = "RIGID_INTERDICTION",
  TIMELY_SUPPRESSION = "TIMELY_SUPPRESSION",
  TEXTBOOK_ASSAULT = "TEXTBOOK_ASSAULT",
  // Gilberta
  BEAM_COHESION_ARTS = "BEAM_COHESION_ARTS",
  GRAVITY_MODE = "GRAVITY_MODE",
  MATRIX_DISPLACEMENT = "MATRIX_DISPLACEMENT",
  GRAVITY_FIELD = "GRAVITY_FIELD",
  // Xaihi
  XAIHI_BASIC_ATTACK = "XAIHI_BASIC_ATTACK",
  DISTRIBUTED_DOS = "DISTRIBUTED_DOS",
  STRESS_TESTING = "STRESS_TESTING",
  STACK_OVERFLOW = "STACK_OVERFLOW",
  // Perlica
  PROTOCOL_ALPHA_BREACH = "PROTOCOL_ALPHA_BREACH",
  PROTOCOL_OMEGA_STRIKE = "PROTOCOL_OMEGA_STRIKE",
  INSTANT_PROTOCOL_CHAIN = "INSTANT_PROTOCOL_CHAIN",
  PROTOCOL_EPSILON = "PROTOCOL_EPSILON",
  // Fluorite
  SIGNATURE_GUN_KATA = "SIGNATURE_GUN_KATA",
  TINY_SURPRISE = "TINY_SURPRISE",
  FREE_GIVEAWAY = "FREE_GIVEAWAY",
  APEX_PRANKSTER = "APEX_PRANKSTER",
  // Last Rite
  DANCE_OF_RIME = "DANCE_OF_RIME",
  ESOTERIC_LEGACY = "ESOTERIC_LEGACY",
  WINTERS_DEVOURER = "WINTERS_DEVOURER",
  VIGIL_SERVICES = "VIGIL_SERVICES",
  // Yvonne
  EXUBERANT_TRIGGER = "EXUBERANT_TRIGGER",
  EXUBERANT_TRIGGER_ENHANCED = "EXUBERANT_TRIGGER_ENHANCED",
  BRR_BRR_BOMB = "BRR_BRR_BOMB",
  FLASHFREEZER = "FLASHFREEZER",
  CRYOBLASTING_PISTOLIER = "CRYOBLASTING_PISTOLIER",
  // Avywenna
  THUNDERLANCE_BLITZ = "THUNDERLANCE_BLITZ",
  THUNDERLANCE_INTERDICTION = "THUNDERLANCE_INTERDICTION",
  THUNDERLANCE_STRIKE = "THUNDERLANCE_STRIKE",
  THUNDERLANCE_FINAL_SHOCK = "THUNDERLANCE_FINAL_SHOCK",
  // Da Pan
  ROLLING_CUT = "ROLLING_CUT",
  FLIP_DA_WOK = "FLIP_DA_WOK",
  MORE_SPICE = "MORE_SPICE",
  CHOP_N_DUNK = "CHOP_N_DUNK",
  // Pogranichnik
  ALL_OUT_OFFENSIVE = "ALL_OUT_OFFENSIVE",
  THE_PULVERIZING_FRONT = "THE_PULVERIZING_FRONT",
  FULL_MOON_SLASH = "FULL_MOON_SLASH",
  SHIELDGUARD_BANNER = "SHIELDGUARD_BANNER",
  // Alesh
  ROD_CASTING = "ROD_CASTING",
  UNCONVENTIONAL_LURE = "UNCONVENTIONAL_LURE",
  AUGER_ANGLING = "AUGER_ANGLING",
  ONE_MONSTER_CATCH = "ONE_MONSTER_CATCH",
  // Arclight
  SEEK_AND_HUNT = "SEEK_AND_HUNT",
  TEMPESTUOUS_ARC = "TEMPESTUOUS_ARC",
  TEMPESTUOUS_ARC_EMPOWERED = "TEMPESTUOUS_ARC_EMPOWERED",
  PEAL_OF_THUNDER = "PEAL_OF_THUNDER",
  EXPLODING_BLITZ = "EXPLODING_BLITZ",
}


export { OperatorInformationType, OperatorType } from '../model/enums/operators';

export enum EnemyType {
  // ── Aggeloi ─────────────────────────────────────────────────────────────────
  RAM = "RAM",
  RAM_ALPHA = "RAM_ALPHA",
  STING = "STING",
  STING_ALPHA = "STING_ALPHA",
  FALSEWINGS = "FALSEWINGS",
  FALSEWINGS_ALPHA = "FALSEWINGS_ALPHA",
  MUDFLOW = "MUDFLOW",
  MUDFLOW_DELTA = "MUDFLOW_DELTA",
  HEDRON = "HEDRON",
  HEDRON_DELTA = "HEDRON_DELTA",
  PRISM = "PRISM",
  HEAVY_RAM = "HEAVY_RAM",
  HEAVY_RAM_ALPHA = "HEAVY_RAM_ALPHA",
  HEAVY_STING = "HEAVY_STING",
  HEAVY_STING_ALPHA = "HEAVY_STING_ALPHA",
  EFFIGY = "EFFIGY",
  SENTINEL = "SENTINEL",
  TIDEWALKER = "TIDEWALKER",
  TIDEWALKER_DELTA = "TIDEWALKER_DELTA",
  WALKING_CHRYSOPOLIS = "WALKING_CHRYSOPOLIS",
  TIDALKLAST = "TIDALKLAST",
  TRIAGGELOS = "TRIAGGELOS",
  MARBLE_AGGELOMOIRAI_PALECORE = "MARBLE_AGGELOMOIRAI_PALECORE",
  MARBLE_AGGELOMOIRAI_PALESENT = "MARBLE_AGGELOMOIRAI_PALESENT",
  MARBLE_APPENDAGE = "MARBLE_APPENDAGE",
  // ── Landbreakers ────────────────────────────────────────────────────────────
  BONEKRUSHER_RIPPTUSK = "BONEKRUSHER_RIPPTUSK",
  ELITE_RIPPTUSK = "ELITE_RIPPTUSK",
  HAZEFYRE_TUSKBEAST = "HAZEFYRE_TUSKBEAST",
  HAZEFYRE_CLAW = "HAZEFYRE_CLAW",
  BONEKRUSHER_RAIDER = "BONEKRUSHER_RAIDER",
  ELITE_RAIDER = "ELITE_RAIDER",
  BONEKRUSHER_AMBUSHER = "BONEKRUSHER_AMBUSHER",
  ELITE_AMBUSHER = "ELITE_AMBUSHER",
  BONEKRUSHER_INFILTRATOR = "BONEKRUSHER_INFILTRATOR",
  BONEKRUSHER_VANGUARD = "BONEKRUSHER_VANGUARD",
  BONEKRUSHER_PYROMANCER = "BONEKRUSHER_PYROMANCER",
  BONEKRUSHER_ARSONIST = "BONEKRUSHER_ARSONIST",
  BONEKRUSHER_BALLISTA = "BONEKRUSHER_BALLISTA",
  BONEKRUSHER_EXECUTIONER = "BONEKRUSHER_EXECUTIONER",
  ELITE_EXECUTIONER = "ELITE_EXECUTIONER",
  BONEKRUSHER_SIEGEKNUCKLES = "BONEKRUSHER_SIEGEKNUCKLES",
  RHODAGN_THE_BONEKRUSHING_FIST = "RHODAGN_THE_BONEKRUSHING_FIST",
  // ── Wildlife ────────────────────────────────────────────────────────────────
  ACID_ORIGINIUM_SLUG = "ACID_ORIGINIUM_SLUG",
  BLAZEMIST_ORIGINIUM_SLUG = "BLAZEMIST_ORIGINIUM_SLUG",
  FIREMIST_ORIGINIUM_SLUG = "FIREMIST_ORIGINIUM_SLUG",
  BRUTAL_PINCERBEAST = "BRUTAL_PINCERBEAST",
  INDIGENOUS_PINCERBEAST = "INDIGENOUS_PINCERBEAST",
  WATERLAMP = "WATERLAMP",
  IMBUED_QUILLBEAST = "IMBUED_QUILLBEAST",
  QUILLBEAST = "QUILLBEAST",
  TUNNELING_NIDWYRM = "TUNNELING_NIDWYRM",
  AXE_ARMORBEAST = "AXE_ARMORBEAST",
  HAZEFYRE_AXE_ARMORBEAST = "HAZEFYRE_AXE_ARMORBEAST",
  GLARING_RAKERBEAST = "GLARING_RAKERBEAST",
  SPOTTED_RAKERBEAST = "SPOTTED_RAKERBEAST",
  // ── Cangzei Pirates ─────────────────────────────────────────────────────────
  GROVE_ARCHER = "GROVE_ARCHER",
  ROAD_PLUNDERER = "ROAD_PLUNDERER",
}

export enum EnemyTierType {
  COMMON = "COMMON",
  ADVANCED = "ADVANCED",
  ELITE = "ELITE",
  ALPHA = "ALPHA",
  BOSS = "BOSS",
}

export enum RaceType {
  LANDBREAKERS = "LANDBREAKERS",
  AGGELOI = "AGGELOI",
  CANGZEI_PIRATES = "CANGZEI_PIRATES",
  WILDLIFE = "WILDLIFE",
}

export enum EnemyLocationType {
  GROUND = "GROUND",
  AIRBORNE = "AIRBORNE",
}

export enum CritMode {
  EXPECTED = 'EXPECTED',
  NONE = 'NONE',
  ALWAYS = 'ALWAYS',
}

export enum DamageType {
  NORMAL = 'NORMAL',
  DAMAGE_OVER_TIME = 'DAMAGE_OVER_TIME',
}


export enum WeaponSkillType {
  // ── Stat boosts (each has _S / _M / _L size variants) ──────────────────────
  ATTACK_BOOST_S = "ATTACK_BOOST_S",
  ATTACK_BOOST_M = "ATTACK_BOOST_M",
  ATTACK_BOOST_L = "ATTACK_BOOST_L",

  STRENGTH_BOOST_S = "STRENGTH_BOOST_S",
  STRENGTH_BOOST_M = "STRENGTH_BOOST_M",
  STRENGTH_BOOST_L = "STRENGTH_BOOST_L",

  AGILITY_BOOST_S = "AGILITY_BOOST_S",
  AGILITY_BOOST_M = "AGILITY_BOOST_M",
  AGILITY_BOOST_L = "AGILITY_BOOST_L",

  INTELLECT_BOOST_S = "INTELLECT_BOOST_S",
  INTELLECT_BOOST_M = "INTELLECT_BOOST_M",
  INTELLECT_BOOST_L = "INTELLECT_BOOST_L",

  WILL_BOOST_S = "WILL_BOOST_S",
  WILL_BOOST_M = "WILL_BOOST_M",
  WILL_BOOST_L = "WILL_BOOST_L",

  MAIN_ATTRIBUTE_BOOST_S = "MAIN_ATTRIBUTE_BOOST_S",
  MAIN_ATTRIBUTE_BOOST_M = "MAIN_ATTRIBUTE_BOOST_M",
  MAIN_ATTRIBUTE_BOOST_L = "MAIN_ATTRIBUTE_BOOST_L",

  PHYSICAL_DAMAGE_BOOST_S = "PHYSICAL_DAMAGE_BOOST_S",
  PHYSICAL_DAMAGE_BOOST_M = "PHYSICAL_DAMAGE_BOOST_M",
  PHYSICAL_DAMAGE_BOOST_L = "PHYSICAL_DAMAGE_BOOST_L",

  HEAT_DAMAGE_BOOST_S = "HEAT_DAMAGE_BOOST_S",
  HEAT_DAMAGE_BOOST_M = "HEAT_DAMAGE_BOOST_M",
  HEAT_DAMAGE_BOOST_L = "HEAT_DAMAGE_BOOST_L",

  CRYO_DAMAGE_BOOST_S = "CRYO_DAMAGE_BOOST_S",
  CRYO_DAMAGE_BOOST_M = "CRYO_DAMAGE_BOOST_M",
  CRYO_DAMAGE_BOOST_L = "CRYO_DAMAGE_BOOST_L",

  NATURE_DAMAGE_BOOST_S = "NATURE_DAMAGE_BOOST_S",
  NATURE_DAMAGE_BOOST_M = "NATURE_DAMAGE_BOOST_M",
  NATURE_DAMAGE_BOOST_L = "NATURE_DAMAGE_BOOST_L",

  ELECTRIC_DAMAGE_BOOST_S = "ELECTRIC_DAMAGE_BOOST_S",
  ELECTRIC_DAMAGE_BOOST_M = "ELECTRIC_DAMAGE_BOOST_M",
  ELECTRIC_DAMAGE_BOOST_L = "ELECTRIC_DAMAGE_BOOST_L",

  ULTIMATE_GAIN_EFFICIENCY_BOOST_S = "ULTIMATE_GAIN_EFFICIENCY_BOOST_S",
  ULTIMATE_GAIN_EFFICIENCY_BOOST_M = "ULTIMATE_GAIN_EFFICIENCY_BOOST_M",
  ULTIMATE_GAIN_EFFICIENCY_BOOST_L = "ULTIMATE_GAIN_EFFICIENCY_BOOST_L",

  HP_BOOST_S = "HP_BOOST_S",
  HP_BOOST_M = "HP_BOOST_M",
  HP_BOOST_L = "HP_BOOST_L",

  ARTS_BOOST_S = "ARTS_BOOST_S",
  ARTS_BOOST_M = "ARTS_BOOST_M",
  ARTS_BOOST_L = "ARTS_BOOST_L",

  ARTS_INTENSITY_BOOST_S = "ARTS_INTENSITY_BOOST_S",
  ARTS_INTENSITY_BOOST_M = "ARTS_INTENSITY_BOOST_M",
  ARTS_INTENSITY_BOOST_L = "ARTS_INTENSITY_BOOST_L",

  CRITICAL_RATE_BOOST_S = "CRITICAL_RATE_BOOST_S",
  CRITICAL_RATE_BOOST_M = "CRITICAL_RATE_BOOST_M",
  CRITICAL_RATE_BOOST_L = "CRITICAL_RATE_BOOST_L",

  TREATMENT_EFFICIENCY_BOOST_S = "TREATMENT_EFFICIENCY_BOOST_S",
  TREATMENT_EFFICIENCY_BOOST_M = "TREATMENT_EFFICIENCY_BOOST_M",
  TREATMENT_EFFICIENCY_BOOST_L = "TREATMENT_EFFICIENCY_BOOST_L",

  // ── Named weapon skills (prefixed by weapon name) ──────────────────────────

  // Sword
  EMINENT_REPUTE_BRUTALITY_DISCIPLINARIAN = "EMINENT_REPUTE_BRUTALITY_DISCIPLINARIAN",
  FORGEBORN_SCATHE_TWILIGHT_BLAZING_WAIL = "FORGEBORN_SCATHE_TWILIGHT_BLAZING_WAIL",
  RAPID_ASCENT_TWILIGHT_AZURE_CLOUDS = "RAPID_ASCENT_TWILIGHT_AZURE_CLOUDS",
  WHITE_NIGHT_NOVA_INFLICTION_WHITE_NIGHT_NOVA = "WHITE_NIGHT_NOVA_INFLICTION_WHITE_NIGHT_NOVA",
  NEVER_REST_FLOW_REINCARNATION = "NEVER_REST_FLOW_REINCARNATION",
  GRAND_VISION_INFLICTION_LONG_TIME_WISH = "GRAND_VISION_INFLICTION_LONG_TIME_WISH",
  THERMITE_CUTTER_FLOW_THERMAL_RELEASE = "THERMITE_CUTTER_FLOW_THERMAL_RELEASE",
  UMBRAL_TORCH_INFLICTION_COVETOUS_BUILDUP = "UMBRAL_TORCH_INFLICTION_COVETOUS_BUILDUP",
  SUNDERING_STEEL_COMBATIVE_ANTHEM_OF_CINDER = "SUNDERING_STEEL_COMBATIVE_ANTHEM_OF_CINDER",
  FORTMAKER_INSPIRING_BACK_TO_THE_BROKEN_CITY = "FORTMAKER_INSPIRING_BACK_TO_THE_BROKEN_CITY",
  ASPIRANT_TWILIGHT_IMPOSING_PEAK = "ASPIRANT_TWILIGHT_IMPOSING_PEAK",
  OBJ_EDGE_OF_LIGHTNESS_FLOW_UNBRIDLED_EDGE = "OBJ_EDGE_OF_LIGHTNESS_FLOW_UNBRIDLED_EDGE",
  TWELVE_QUESTIONS_INFLICTION_SINCERE_INTERROGATION = "TWELVE_QUESTIONS_INFLICTION_SINCERE_INTERROGATION",
  FINCHASER_3_0_SUPPRESSION_FIN_CHASERS_INTENT = "FINCHASER_3_0_SUPPRESSION_FIN_CHASERS_INTENT",
  WAVE_TIDE_PURSUIT_UNENDING_CYCLE = "WAVE_TIDE_PURSUIT_UNENDING_CYCLE",
  CONTINGENT_MEASURE_SUPPRESSION_EMERGENCY_BOOST = "CONTINGENT_MEASURE_SUPPRESSION_EMERGENCY_BOOST",
  TARR_11_ASSAULT_ARMAMENT_PREP = "TARR_11_ASSAULT_ARMAMENT_PREP",

  // Great Sword
  FORMER_FINERY_MINCING_THERAPY = "FORMER_FINERY_MINCING_THERAPY",
  SUNDERED_PRINCE_CRUSHER_PRINCELY_DETERRENCE = "SUNDERED_PRINCE_CRUSHER_PRINCELY_DETERRENCE",
  THUNDERBERGE_MEDICANT_EYE_OF_TALOS = "THUNDERBERGE_MEDICANT_EYE_OF_TALOS",
  EXEMPLAR_SUPPRESSION_STACKED_HEW = "EXEMPLAR_SUPPRESSION_STACKED_HEW",
  KHRAVENGGER_DETONATE_BONECHILLING = "KHRAVENGGER_DETONATE_BONECHILLING",
  OBJ_HEAVY_BURDEN_EFFICACY_TENACIOUS_WILL = "OBJ_HEAVY_BURDEN_EFFICACY_TENACIOUS_WILL",
  FINISHING_CALL_MEDICANT_GLORY_OF_KNIGHTHOOD = "FINISHING_CALL_MEDICANT_GLORY_OF_KNIGHTHOOD",
  ANCIENT_CANAL_BRUTALITY_LANDS_OF_YORE = "ANCIENT_CANAL_BRUTALITY_LANDS_OF_YORE",
  SEEKER_OF_DARK_LUNG_DETONATE_SEEKER_OF_THE_ESOTERIC = "SEEKER_OF_DARK_LUNG_DETONATE_SEEKER_OF_THE_ESOTERIC",
  INDUSTRY_0_1_SUPPRESSION_EMERGENCY_BOOST = "INDUSTRY_0_1_SUPPRESSION_EMERGENCY_BOOST",
  QUENCHER_CRUSHER_HONED_INTO_LEGION = "QUENCHER_CRUSHER_HONED_INTO_LEGION",
  DARHOFF_7_ASSAULT_ARMAMENT_PREP = "DARHOFF_7_ASSAULT_ARMAMENT_PREP",

  // Polearm
  JET_SUPPRESSION_ASTROPHYSICS = "JET_SUPPRESSION_ASTROPHYSICS",
  MOUNTAIN_BEARER_WEIGHT_OF_MOUNTAIN = "MOUNTAIN_BEARER_WEIGHT_OF_MOUNTAIN",
  VALIANT_COMBATIVE_VIRTUOUS_GAIN = "VALIANT_COMBATIVE_VIRTUOUS_GAIN",
  COHESIVE_TRACTION_SUPPRESSION_CONCENTRIC_CIRCLES = "COHESIVE_TRACTION_SUPPRESSION_CONCENTRIC_CIRCLES",
  CHIMERIC_JUSTICE_BRUTALITY_CEMENTED_FURY = "CHIMERIC_JUSTICE_BRUTALITY_CEMENTED_FURY",
  OBJ_RAZORHORN_INFLICTION_CONQUEST_OF_ICY_PEAKS = "OBJ_RAZORHORN_INFLICTION_CONQUEST_OF_ICY_PEAKS",
  PATHFINDERS_BEACON_INSPIRING_START_OF_A_SAGA = "PATHFINDERS_BEACON_INSPIRING_START_OF_A_SAGA",
  AGGELOSLAYER_SUPPRESSION_EMERGENCY_BOOST = "AGGELOSLAYER_SUPPRESSION_EMERGENCY_BOOST",
  OPERO_77_ASSAULT_ARMAMENT_PREP = "OPERO_77_ASSAULT_ARMAMENT_PREP",

  // Handcannon
  WEDGE_INFLICTION_WEDGE_OF_CIVILIZATION = "WEDGE_INFLICTION_WEDGE_OF_CIVILIZATION",
  NAVIGATOR_INFLICTION_LONE_AND_DISTANT_SAIL = "NAVIGATOR_INFLICTION_LONE_AND_DISTANT_SAIL",
  ARTZY_TYRANNICAL_FRACTURE_ARTZY_EXAGGERATION = "ARTZY_TYRANNICAL_FRACTURE_ARTZY_EXAGGERATION",
  RATIONAL_FAREWELL_PURSUIT_AID_FROM_THE_PAST = "RATIONAL_FAREWELL_PURSUIT_AID_FROM_THE_PAST",
  OPUS_THE_LIVING_INFLICTION_ROAD_HOME_FOR_ALL_LIFE = "OPUS_THE_LIVING_INFLICTION_ROAD_HOME_FOR_ALL_LIFE",
  OBJ_VELOCITOUS_DETONATE_RAPID_STRIKE = "OBJ_VELOCITOUS_DETONATE_RAPID_STRIKE",
  HOWLING_GUARD_SUPPRESSION_EMERGENCY_BOOST = "HOWLING_GUARD_SUPPRESSION_EMERGENCY_BOOST",
  LONG_ROAD_PURSUIT_UNENDING_CYCLE = "LONG_ROAD_PURSUIT_UNENDING_CYCLE",
  CLANNIBAL_INFLICTION_VICIOUS_PURGE = "CLANNIBAL_INFLICTION_VICIOUS_PURGE",
  PECO_5_ASSAULT_ARMAMENT_PREP = "PECO_5_ASSAULT_ARMAMENT_PREP",

  // Arts Unit
  CHIVALRIC_VIRTUES_MEDICANT_BLIGHT_FERVOR = "CHIVALRIC_VIRTUES_MEDICANT_BLIGHT_FERVOR",
  DETONATION_UNIT_DETONATE_IMPOSING_CHAMPION = "DETONATION_UNIT_DETONATE_IMPOSING_CHAMPION",
  OBLIVION_TWILIGHT_HUMILIATION = "OBLIVION_TWILIGHT_HUMILIATION",
  OPUS_ETCH_FIGURE_SUPPRESSION_TILLITE_ETCHINGS = "OPUS_ETCH_FIGURE_SUPPRESSION_TILLITE_ETCHINGS",
  DELIVERY_GUARANTEED_PURSUIT_DUTY_FULFILLED = "DELIVERY_GUARANTEED_PURSUIT_DUTY_FULFILLED",
  OBJ_ARTS_IDENTIFIER_PURSUIT_TRANSCENDENT_ARTS = "OBJ_ARTS_IDENTIFIER_PURSUIT_TRANSCENDENT_ARTS",
  FREEDOM_TO_PROSELYTIZE_MEDICANT_REDEMPTION_OF_FAITH = "FREEDOM_TO_PROSELYTIZE_MEDICANT_REDEMPTION_OF_FAITH",
  WILD_WANDERER_INFLICTION_WILDERNESS_CLUSTER = "WILD_WANDERER_INFLICTION_WILDERNESS_CLUSTER",
  MONAIHE_INSPIRING_MORTISE_AND_TENON_ANALYSIS = "MONAIHE_INSPIRING_MORTISE_AND_TENON_ANALYSIS",
  FLUORESCENT_ROC_SUPPRESSION_EMERGENCY_BOOST = "FLUORESCENT_ROC_SUPPRESSION_EMERGENCY_BOOST",
  HYPERNOVA_AUTO_INSPIRING_START_OF_A_SAGA = "HYPERNOVA_AUTO_INSPIRING_START_OF_A_SAGA",
  JIMINY_12_ASSAULT_ARMAMENT_PREP = "JIMINY_12_ASSAULT_ARMAMENT_PREP",
  STANZA_OF_MEMORIALS_TWILIGHT_LUSTROUS_PYRE = "STANZA_OF_MEMORIALS_TWILIGHT_LUSTROUS_PYRE",
  DREAMS_OF_THE_STARRY_BEACH_INFLICTION_TIDAL_MURMURS = "DREAMS_OF_THE_STARRY_BEACH_INFLICTION_TIDAL_MURMURS",
}
