export enum CombatSkillType {
  BASIC_ATTACK = "BASIC_ATTACK",
  BATTLE_SKILL = "BATTLE_SKILL",
  COMBO_SKILL = "COMBO_SKILL",
  ULTIMATE = "ULTIMATE",
}

export enum MainStatType {
  BASE_HP = "BASE_HP",
  HP_FROM_STRENGTH = "HP_FROM_STRENGTH",
  BASE_ATTACK = "BASE_ATTACK",
  ATTACK_BONUS = "ATTACK_BONUS",
  DEFENSE = "DEFENSE",
}

export enum CombatResourceType {
  SKILL_POINT = "SKILL_POINT",
  ULTIMATE_ENERGY = "ULTIMATE_ENERGY",
}

export enum EventFrameType {
  NORMAL = "NORMAL",
  FINAL_STRIKE = "FINAL_STRIKE",
  FINISHER = "FINISHER",
  DIVE = "DIVE",
}

export enum EventStatusType {
  EXPIRED = "EXPIRED",
  CONSUMED = "CONSUMED",
  REFRESHED = "REFRESHED",
  TRIGGERED = "TRIGGERED",
  EXTENDED = "EXTENDED",
}

export enum ElementType {
  NONE = "NONE",
  PHYSICAL = "PHYSICAL",
  HEAT = "HEAT",
  CRYO = "CRYO",
  NATURE = "NATURE",
  ELECTRIC = "ELECTRIC",
}

/** Maps status types to their associated element (for coloring). */
export const STATUS_ELEMENT: Record<string, string> = {
  MELTING_FLAME:    ElementType.HEAT,
  COMBUSTION:       ElementType.HEAT,
  SOLIDIFICATION:   ElementType.CRYO,
  CRIT_STACKS:      ElementType.CRYO,
  CORROSION:        ElementType.NATURE,
  ELECTRIFICATION:  ElementType.ELECTRIC,
  THUNDERLANCE:     ElementType.ELECTRIC,
};

export const ELEMENT_LABELS: Record<ElementType, string> = {
  [ElementType.NONE]:     'None',
  [ElementType.PHYSICAL]: 'Physical',
  [ElementType.HEAT]:     'Heat',
  [ElementType.CRYO]:     'Cryo',
  [ElementType.NATURE]:   'Nature',
  [ElementType.ELECTRIC]: 'Electric',
};

export const ELEMENT_COLORS: Record<ElementType, string> = {
  [ElementType.NONE]:     '#cccccc',
  [ElementType.PHYSICAL]: '#b0b8c0',
  [ElementType.HEAT]:     '#e85535',
  [ElementType.CRYO]:     '#55ccee',
  [ElementType.NATURE]:   '#55cc55',
  [ElementType.ELECTRIC]: '#e8c840',
};

export enum StatusType {
  // ── Arts reactions ──────────────────────────────────────────────────────────
  COMBUSTION = "COMBUSTION",
  SOLIDIFICATION = "SOLIDIFICATION",
  CORROSION = "CORROSION",
  ELECTRIFICATION = "ELECTRIFICATION",
  // ── Operator buffs ─────────────────────────────────────────────────────────
  MELTING_FLAME = "MELTING_FLAME",
  THUNDERLANCE = "THUNDERLANCE",
  CRIT_STACKS = "CRIT_STACKS",
  SQUAD_BUFF = "SQUAD_BUFF",
  SCORCHING_FANGS = "SCORCHING_FANGS",
  // ── Team statuses ─────────────────────────────────────────────────────────
  LINK = "LINK",
  ARTS_AMP = "ARTS_AMP",
  SHIELD = "SHIELD",
  UNBRIDLED_EDGE = "UNBRIDLED_EDGE",
  WILDLAND_TREKKER = "WILDLAND_TREKKER",
  MESSENGERS_SONG = "MESSENGERS_SONG",
  // ── Enemy debuffs ─────────────────────────────────────────────────────────
  SCORCHING_HEART = "SCORCHING_HEART",
  FOCUS = "FOCUS",
  SUSCEPTIBILITY = "SUSCEPTIBILITY",
  FRAGILITY = "FRAGILITY",
  ORIGINIUM_CRYSTAL = "ORIGINIUM_CRYSTAL",
  WEAKEN = "WEAKEN",
  DMG_REDUCTION = "DMG_REDUCTION",
  PROTECTION = "PROTECTION",
  // ── Physical statuses ───────────────────────────────────────────────────────
  LIFT = "LIFT",
  KNOCK_DOWN = "KNOCK_DOWN",
  CRUSH = "CRUSH",
  BREACH = "BREACH",
}

/** Damage formula multiplier factor that a status contributes to. */
export enum DamageFactorType {
  NONE = "NONE",
  MULTIPLIER_GROUP = "MULTIPLIER_GROUP",
  AMP = "AMP",
  STAGGER = "STAGGER",
  LINK = "LINK",
  WEAKEN = "WEAKEN",
  SUSCEPTIBILITY = "SUSCEPTIBILITY",
  FRAGILITY = "FRAGILITY",
  DMG_REDUCTION = "DMG_REDUCTION",
  PROTECTION = "PROTECTION",
  DEFENSE = "DEFENSE",
  RESISTANCE = "RESISTANCE",
}

/** Maps each StatusType to the damage formula factor it contributes to. */
export const STATUS_DAMAGE_FACTOR: Record<StatusType, DamageFactorType> = {
  // Arts reactions — deal damage, don't directly map to a single multiplier factor
  [StatusType.COMBUSTION]: DamageFactorType.NONE,
  [StatusType.SOLIDIFICATION]: DamageFactorType.NONE,
  [StatusType.CORROSION]: DamageFactorType.RESISTANCE,
  [StatusType.ELECTRIFICATION]: DamageFactorType.FRAGILITY,
  // Operator buffs
  [StatusType.MELTING_FLAME]: DamageFactorType.NONE,
  [StatusType.THUNDERLANCE]: DamageFactorType.NONE,
  [StatusType.CRIT_STACKS]: DamageFactorType.NONE,
  [StatusType.SQUAD_BUFF]: DamageFactorType.MULTIPLIER_GROUP,
  [StatusType.SCORCHING_FANGS]: DamageFactorType.RESISTANCE,
  // Team statuses
  [StatusType.LINK]: DamageFactorType.LINK,
  [StatusType.ARTS_AMP]: DamageFactorType.AMP,
  [StatusType.SHIELD]: DamageFactorType.NONE,
  [StatusType.UNBRIDLED_EDGE]: DamageFactorType.MULTIPLIER_GROUP,
  [StatusType.WILDLAND_TREKKER]: DamageFactorType.MULTIPLIER_GROUP,
  [StatusType.SCORCHING_HEART]: DamageFactorType.RESISTANCE,
  // Enemy debuffs
  [StatusType.FOCUS]: DamageFactorType.SUSCEPTIBILITY,
  [StatusType.SUSCEPTIBILITY]: DamageFactorType.SUSCEPTIBILITY,
  [StatusType.FRAGILITY]: DamageFactorType.FRAGILITY,
  [StatusType.ORIGINIUM_CRYSTAL]: DamageFactorType.FRAGILITY,
  [StatusType.WEAKEN]: DamageFactorType.WEAKEN,
  [StatusType.DMG_REDUCTION]: DamageFactorType.DMG_REDUCTION,
  [StatusType.PROTECTION]: DamageFactorType.PROTECTION,
  // Physical statuses
  [StatusType.LIFT]: DamageFactorType.STAGGER,
  [StatusType.KNOCK_DOWN]: DamageFactorType.STAGGER,
  [StatusType.CRUSH]: DamageFactorType.NONE,
  [StatusType.BREACH]: DamageFactorType.FRAGILITY,
  // Team passives
  [StatusType.MESSENGERS_SONG]: DamageFactorType.NONE,
};

/** Elemental inflictions that can be applied to a target, plus the universal VULNERABLE debuff. */
export enum InflictionType {
  HEAT_INFLICTION = "HEAT_INFLICTION",
  CRYO_INFLICTION = "CRYO_INFLICTION",
  NATURE_INFLICTION = "NATURE_INFLICTION",
  ELECTRIC_INFLICTION = "ELECTRIC_INFLICTION",
  VULNERABLE = "VULNERABLE",
}

/** Subset of InflictionType — the four elemental inflictions that trigger ArtsReactions. */
export enum ArtsInflictionType {
  HEAT_INFLICTION = "HEAT_INFLICTION",
  CRYO_INFLICTION = "CRYO_INFLICTION",
  NATURE_INFLICTION = "NATURE_INFLICTION",
  ELECTRIC_INFLICTION = "ELECTRIC_INFLICTION",
}

export enum OperatorClassType {
  GUARD = "GUARD",
  CASTER = "CASTER",
  STRIKER = "STRIKER",
  VANGUARD = "VANGUARD",
  DEFENDER = "DEFENDER",
  SUPPORTER = "SUPPORTER",
}

export enum WeaponType {
  SWORD = "SWORD",
  GREAT_SWORD = "GREAT_SWORD",
  POLEARM = "POLEARM",
  HANDCANNON = "HANDCANNON",
  ARTS_UNIT = "ARTS_UNIT",
}

export enum GearType {
  ARMOR = "ARMOR",
  GLOVES = "GLOVES",
  KIT = "KIT",
}

export enum BasicAttackType {
  SEQUENCE_1 = "SEQUENCE_1",
  SEQUENCE_2 = "SEQUENCE_2",
  SEQUENCE_3 = "SEQUENCE_3",
  SEQUENCE_4 = "SEQUENCE_4",
  SEQUENCE_5 = "SEQUENCE_5",
  FINISHER = "FINISHER",
  DIVE = "DIVE",
  FINAL_STRIKE = "FINAL_STRIKE",
}

/** Conditions that can trigger a skill effect eg. combo skill. */
export enum TriggerConditionType {
  SKILL_POINT_RECOVERY_FROM_SKILL = "SKILL_POINT_RECOVERY_FROM_SKILL",
  FINAL_STRIKE = "FINAL_STRIKE",
  COMBUSTION = "COMBUSTION",
  SOLIDIFICATION = "SOLIDIFICATION",
  CORROSION = "CORROSION",
  ELECTRIFICATION = "ELECTRIFICATION",
  DEFEAT_ENEMY = "DEFEAT_ENEMY",
  CAST_BATTLE_SKILL = "CAST_BATTLE_SKILL",
  CAST_COMBO_SKILL = "CAST_COMBO_SKILL",
  CAST_ULTIMATE = "CAST_ULTIMATE",
  APPLY_PHYSICAL_STATUS = "APPLY_PHYSICAL_STATUS",
  APPLY_VULNERABILITY = "APPLY_VULNERABILITY",
  CRITICAL_HIT = "CRITICAL_HIT",
  HP_TREATMENT = "HP_TREATMENT",
  HP_TREATMENT_EXCEEDS_MAX = "HP_TREATMENT_EXCEEDS_MAX",
  TEAM_CAST_BATTLE_SKILL = "TEAM_CAST_BATTLE_SKILL",
  APPLY_ARTS_INFLICTION = "APPLY_ARTS_INFLICTION",
  APPLY_HEAT_INFLICTION = "APPLY_HEAT_INFLICTION",
  APPLY_CRYO_INFLICTION = "APPLY_CRYO_INFLICTION",
  APPLY_NATURE_INFLICTION = "APPLY_NATURE_INFLICTION",
  APPLY_ELECTRIC_INFLICTION = "APPLY_ELECTRIC_INFLICTION",
  APPLY_ARTS_INFLICTION_2_STACKS = "APPLY_ARTS_INFLICTION_2_STACKS",
  APPLY_BUFF = "APPLY_BUFF",
  HP_ABOVE_THRESHOLD = "HP_ABOVE_THRESHOLD",
  HP_BELOW_THRESHOLD = "HP_BELOW_THRESHOLD",
  ULTIMATE_ENERGY_BELOW_THRESHOLD = "ULTIMATE_ENERGY_BELOW_THRESHOLD",
  OPERATOR_ATTACKED = "OPERATOR_ATTACKED",
  STAGGER = "STAGGER",
  STAGGER_NODE = "STAGGER_NODE",
  // ── Weapon skill triggers ─────────────────────────────────────────────────
  CONSUME_VULNERABILITY = "CONSUME_VULNERABILITY",
  APPLY_ARTS_REACTION = "APPLY_ARTS_REACTION",
  CONSUME_ARTS_REACTION = "CONSUME_ARTS_REACTION",
  APPLY_LIFTED = "APPLY_LIFTED",
  APPLY_KNOCKED_DOWN = "APPLY_KNOCKED_DOWN",
  APPLY_ARTS_BURST = "APPLY_ARTS_BURST",
  CONSUME_CORROSION = "CONSUME_CORROSION",
}

/**
 * Subset relationships: if a publisher publishes a specific type (e.g.
 * APPLY_HEAT_INFLICTION), listeners for the parent type (APPLY_ARTS_INFLICTION)
 * should also match.
 */
export const TRIGGER_CONDITION_PARENTS: Partial<Record<TriggerConditionType, TriggerConditionType>> = {
  [TriggerConditionType.APPLY_HEAT_INFLICTION]:     TriggerConditionType.APPLY_ARTS_INFLICTION,
  [TriggerConditionType.APPLY_CRYO_INFLICTION]:     TriggerConditionType.APPLY_ARTS_INFLICTION,
  [TriggerConditionType.APPLY_NATURE_INFLICTION]:   TriggerConditionType.APPLY_ARTS_INFLICTION,
  [TriggerConditionType.APPLY_ELECTRIC_INFLICTION]: TriggerConditionType.APPLY_ARTS_INFLICTION,
};

export enum GearEffectType {
  NONE = "NONE",
  AIC_HEAVY = "AIC_HEAVY",
  AIC_LIGHT = "AIC_LIGHT",
  ARMORED_MSGR = "ARMORED_MSGR",
  ROVING_MSGR = "ROVING_MSGR",
  MORDVOLT_INSULATION = "MORDVOLT_INSULATION",
  MORDVOLT_RESISTANT = "MORDVOLT_RESISTANT",
  ABURREY_LEGACY = "ABURREY_LEGACY",
  CATASTROPHE = "CATASTROPHE",
  SWORDMANCER = "SWORDMANCER",
  LYNX = "LYNX",
  AETHERTECH = "AETHERTECH",
  BONEKRUSHA = "BONEKRUSHA",
  PULSER_LABS = "PULSER_LABS",
  FRONTIERS = "FRONTIERS",
  HOT_WORK = "HOT_WORK",
  MI_SECURITY = "MI_SECURITY",
  TYPE_50_YINGLUNG = "TYPE_50_YINGLUNG",
  TIDE_SURGE = "TIDE_SURGE",
  ETERNAL_XIRANITE = "ETERNAL_XIRANITE",
}

export enum EventType {
  COMBAT_SKILL = "COMBAT_SKILL",
  STATUS = "STATUS",
}

/** Time manipulation effects that prevent other events from starting. */
export enum TimeInteractionType {
  /** No interaction with other timelines — purely cosmetic/tracking. */
  NONE = "NONE",
  /** No other events can start on any timeline while this is active. */
  TIME_STOP = "TIME_STOP",
  /** Delays all other timelines by this event's duration (e.g. dash with dodge). */
  TIME_DELAY = "TIME_DELAY",
}

/** Whether an event segment's duration is tied to game-time (affected by time-stops) or real-time (unaffected). */
export enum TimeDependency {
  GAME_TIME = "GAME_TIME",
  REAL_TIME = "REAL_TIME",
}

export enum TimelineSourceType {
  OPERATOR = "OPERATOR",
  GEAR_EFFECT = "GEAR_EFFECT",
  WEAPON = "WEAPON",
  ENEMY = "ENEMY",
  COMMON = "COMMON",
  TACTICAL = "TACTICAL",
  DEBUGGER = "DEBUGGER",
}

export enum TargetType {
  ENEMY = "ENEMY",
  SELF = "SELF",
  TEAM = "TEAM",
  TEAM_MEMBER = "TEAM_MEMBER",
}

export enum StatType {
  // ── Attributes ───────────────────────────────────────────────────────────────
  // _BONUS suffix = non-flat multiplicative factor (e.g. 0.10 = ×1.10)
  BASE_HP = "BASE_HP",
  DEFENSE = "DEFENSE",
  ATTACK = "ATTACK",
  ATTACK_BONUS = "ATTACK_BONUS",
  STRENGTH = "STRENGTH",
  STRENGTH_BONUS = "STRENGTH_BONUS",
  AGILITY = "AGILITY",
  AGILITY_BONUS = "AGILITY_BONUS",
  INTELLECT = "INTELLECT",
  INTELLECT_BONUS = "INTELLECT_BONUS",
  WILL = "WILL",
  WILL_BONUS = "WILL_BONUS",
  // ── Combat stats ─────────────────────────────────────────────────────────────
  CRITICAL_RATE = "CRITICAL_RATE",
  CRITICAL_DAMAGE = "CRITICAL_DAMAGE",
  ARTS_INTENSITY = "ARTS_INTENSITY",
  PHYSICAL_RESISTANCE = "PHYSICAL_RESISTANCE",
  HEAT_RESISTANCE = "HEAT_RESISTANCE",
  ELECTRIC_RESISTANCE = "ELECTRIC_RESISTANCE",
  CRYO_RESISTANCE = "CRYO_RESISTANCE",
  NATURE_RESISTANCE = "NATURE_RESISTANCE",
  AETHER_RESISTANCE = "AETHER_RESISTANCE",
  TREATMENT_BONUS = "TREATMENT_BONUS",
  TREATMENT_RECEIVED_BONUS = "TREATMENT_RECEIVED_BONUS",
  COMBO_SKILL_COOLDOWN_REDUCTION = "COMBO_SKILL_COOLDOWN_REDUCTION",
  ULTIMATE_GAIN_EFFICIENCY = "ULTIMATE_GAIN_EFFICIENCY",
  STAGGER_EFFICIENCY_BONUS = "STAGGER_EFFICIENCY_BONUS",
  PHYSICAL_DAMAGE_BONUS = "PHYSICAL_DAMAGE_BONUS",
  HEAT_DAMAGE_BONUS = "HEAT_DAMAGE_BONUS",
  ELECTRIC_DAMAGE_BONUS = "ELECTRIC_DAMAGE_BONUS",
  CRYO_DAMAGE_BONUS = "CRYO_DAMAGE_BONUS",
  NATURE_DAMAGE_BONUS = "NATURE_DAMAGE_BONUS",
  BASIC_ATTACK_DAMAGE_BONUS = "BASIC_ATTACK_DAMAGE_BONUS",
  BATTLE_SKILL_DAMAGE_BONUS = "BATTLE_SKILL_DAMAGE_BONUS",
  COMBO_SKILL_DAMAGE_BONUS = "COMBO_SKILL_DAMAGE_BONUS",
  ULTIMATE_DAMAGE_BONUS = "ULTIMATE_DAMAGE_BONUS",
  STAGGER_DAMAGE_BONUS = "STAGGER_DAMAGE_BONUS",
  FINAL_DAMAGE_REDUCTION = "FINAL_DAMAGE_REDUCTION",
  SKILL_DAMAGE_BONUS = "SKILL_DAMAGE_BONUS",
  ARTS_DAMAGE_BONUS = "ARTS_DAMAGE_BONUS",
  HP_BONUS = "HP_BONUS",
  FLAT_HP = "FLAT_HP",
}

export enum CombatSkillsType {
  // Common
  DASH = "DASH",
  FINISHER = "FINISHER",
  DIVE = "DIVE",

  // Laevatain
  FLAMING_CINDERS = "FLAMING_CINDERS",
  FLAMING_CINDERS_ENHANCED = "FLAMING_CINDERS_ENHANCED",
  SMOULDERING_FIRE = "SMOULDERING_FIRE",
  SMOULDERING_FIRE_ENHANCED = "SMOULDERING_FIRE_ENHANCED",
  SMOULDERING_FIRE_EMPOWERED = "SMOULDERING_FIRE_EMPOWERED",
  SMOULDERING_FIRE_ENHANCED_EMPOWERED = "SMOULDERING_FIRE_ENHANCED_EMPOWERED",
  SEETHE = "SEETHE",
  TWILIGHT = "TWILIGHT",
  // Antal
  EXCHANGE_CURRENT = "EXCHANGE_CURRENT",
  SPECIFIED_RESEARCH_SUBJECT = "SPECIFIED_RESEARCH_SUBJECT",
  EMP_TEST_SITE = "EMP_TEST_SITE",
  OVERCLOCKED_MOMENT = "OVERCLOCKED_MOMENT",
  // Akekuri
  SWORD_OF_ASPIRATION = "SWORD_OF_ASPIRATION",
  BURST_OF_PASSION = "BURST_OF_PASSION",
  FLASH_AND_DASH = "FLASH_AND_DASH",
  SQUAD_ON_ME = "SQUAD_ON_ME",
  // Wulfgard
  RAPID_FIRE_AKIMBO = "RAPID_FIRE_AKIMBO",
  THERMITE_TRACERS = "THERMITE_TRACERS",
  FRAG_GRENADE_BETA = "FRAG_GRENADE_BETA",
  WOLVEN_FURY = "WOLVEN_FURY",
  // Ardelia
  ROCKY_WHISPERS = "ROCKY_WHISPERS",
  DOLLY_RUSH = "DOLLY_RUSH",
  ERUPTION_COLUMN = "ERUPTION_COLUMN",
  WOOLY_PARTY = "WOOLY_PARTY",
  // Endministrator
  DESTRUCTIVE_SEQUENCE = "DESTRUCTIVE_SEQUENCE",
  CONSTRUCTIVE_SEQUENCE = "CONSTRUCTIVE_SEQUENCE",
  SEALING_SEQUENCE = "SEALING_SEQUENCE",
  BOMBARDMENT_SEQUENCE = "BOMBARDMENT_SEQUENCE",
  // Lifeng
  RUINATION = "RUINATION",
  TURBID_AVATAR = "TURBID_AVATAR",
  ASPECT_OF_WRATH = "ASPECT_OF_WRATH",
  HEART_OF_THE_UNMOVING = "HEART_OF_THE_UNMOVING",
  // Chen Qianyu
  SOARING_BREAK = "SOARING_BREAK",
  ASCENDING_STRIKE = "ASCENDING_STRIKE",
  SOAR_TO_THE_STARS = "SOAR_TO_THE_STARS",
  BLADE_GALE = "BLADE_GALE",
  // Estella
  AUDIO_NOISE = "AUDIO_NOISE",
  ONOMATOPOEIA = "ONOMATOPOEIA",
  DISTORTION = "DISTORTION",
  TREMOLO = "TREMOLO",
  // Ember
  SWORD_ART_OF_ASSAULT = "SWORD_ART_OF_ASSAULT",
  FORWARD_MARCH = "FORWARD_MARCH",
  FRONTLINE_SUPPORT = "FRONTLINE_SUPPORT",
  RE_IGNITED_OATH = "RE_IGNITED_OATH",
  // Snowshine
  HYPOTHERMIC_ASSAULT = "HYPOTHERMIC_ASSAULT",
  SATURATED_DEFENSE = "SATURATED_DEFENSE",
  POLAR_RESCUE = "POLAR_RESCUE",
  FRIGID_SNOWFIELD = "FRIGID_SNOWFIELD",
  // Catcher
  RIGID_INTERDICTION_BASIC = "RIGID_INTERDICTION_BASIC",
  RIGID_INTERDICTION = "RIGID_INTERDICTION",
  TIMELY_SUPPRESSION = "TIMELY_SUPPRESSION",
  TEXTBOOK_ASSAULT = "TEXTBOOK_ASSAULT",
  // Gilberta
  BEAM_COHESION_ARTS = "BEAM_COHESION_ARTS",
  GRAVITY_MODE = "GRAVITY_MODE",
  MATRIX_DISPLACEMENT = "MATRIX_DISPLACEMENT",
  GRAVITY_FIELD = "GRAVITY_FIELD",
  // Xaihi
  XAIHI_BASIC_ATTACK = "XAIHI_BASIC_ATTACK",
  DISTRIBUTED_DOS = "DISTRIBUTED_DOS",
  STRESS_TESTING = "STRESS_TESTING",
  STACK_OVERFLOW = "STACK_OVERFLOW",
  // Perlica
  PROTOCOL_ALPHA_BREACH = "PROTOCOL_ALPHA_BREACH",
  PROTOCOL_OMEGA_STRIKE = "PROTOCOL_OMEGA_STRIKE",
  INSTANT_PROTOCOL_CHAIN = "INSTANT_PROTOCOL_CHAIN",
  PROTOCOL_EPSILON = "PROTOCOL_EPSILON",
  // Fluorite
  SIGNATURE_GUN_KATA = "SIGNATURE_GUN_KATA",
  TINY_SURPRISE = "TINY_SURPRISE",
  FREE_GIVEAWAY = "FREE_GIVEAWAY",
  APEX_PRANKSTER = "APEX_PRANKSTER",
  // Last Rite
  DANCE_OF_RIME = "DANCE_OF_RIME",
  ESOTERIC_LEGACY = "ESOTERIC_LEGACY",
  WINTERS_DEVOURER = "WINTERS_DEVOURER",
  VIGIL_SERVICES = "VIGIL_SERVICES",
  // Yvonne
  EXUBERANT_TRIGGER = "EXUBERANT_TRIGGER",
  EXUBERANT_TRIGGER_ENHANCED = "EXUBERANT_TRIGGER_ENHANCED",
  BRR_BRR_BOMB = "BRR_BRR_BOMB",
  FLASHFREEZER = "FLASHFREEZER",
  CRYOBLASTING_PISTOLIER = "CRYOBLASTING_PISTOLIER",
  // Avywenna
  THUNDERLANCE_BLITZ = "THUNDERLANCE_BLITZ",
  THUNDERLANCE_INTERDICTION = "THUNDERLANCE_INTERDICTION",
  THUNDERLANCE_STRIKE = "THUNDERLANCE_STRIKE",
  THUNDERLANCE_FINAL_SHOCK = "THUNDERLANCE_FINAL_SHOCK",
  // Da Pan
  ROLLING_CUT = "ROLLING_CUT",
  FLIP_DA_WOK = "FLIP_DA_WOK",
  MORE_SPICE = "MORE_SPICE",
  CHOP_N_DUNK = "CHOP_N_DUNK",
  // Pogranichnik
  ALL_OUT_OFFENSIVE = "ALL_OUT_OFFENSIVE",
  THE_PULVERIZING_FRONT = "THE_PULVERIZING_FRONT",
  FULL_MOON_SLASH = "FULL_MOON_SLASH",
  SHIELDGUARD_BANNER = "SHIELDGUARD_BANNER",
  // Alesh
  ROD_CASTING = "ROD_CASTING",
  UNCONVENTIONAL_LURE = "UNCONVENTIONAL_LURE",
  AUGER_ANGLING = "AUGER_ANGLING",
  ONE_MONSTER_CATCH = "ONE_MONSTER_CATCH",
  // Arclight
  SEEK_AND_HUNT = "SEEK_AND_HUNT",
  TEMPESTUOUS_ARC = "TEMPESTUOUS_ARC",
  PEAL_OF_THUNDER = "PEAL_OF_THUNDER",
  EXPLODING_BLITZ = "EXPLODING_BLITZ",
}

export enum SkillDataKey {
  DURATION = "DURATION",
  SP_COST = "SP_COST",
  GAUGE_GAIN = "GAUGE_GAIN",
  TEAM_GAUGE_GAIN = "TEAM_GAUGE_GAIN",
  COOLDOWN = "COOLDOWN",
  TICKS = "TICKS",
  ANIMATION_TIME = "ANIMATION_TIME",
  ENERGY_COST = "ENERGY_COST",
}

export enum DamageTickKey {
  OFFSET_SECONDS = "OFFSET_SECONDS",
  SKILL_POINT_RECOVERY = "SKILL_POINT_RECOVERY",
  STAGGER = "STAGGER",
}

export enum OperatorType {
  LAEVATAIN = "LAEVATAIN",
  AKEKURI = "AKEKURI",
  ANTAL = "ANTAL",
  ARDELIA = "ARDELIA",
  WULFGARD = "WULFGARD",
  ENDMINISTRATOR = "ENDMINISTRATOR",
  LIFENG = "LIFENG",
  CHEN_QIANYU = "CHEN_QIANYU",
  ESTELLA = "ESTELLA",
  EMBER = "EMBER",
  SNOWSHINE = "SNOWSHINE",
  CATCHER = "CATCHER",
  GILBERTA = "GILBERTA",
  XAIHI = "XAIHI",
  PERLICA = "PERLICA",
  FLUORITE = "FLUORITE",
  LAST_RITE = "LAST_RITE",
  YVONNE = "YVONNE",
  AVYWENNA = "AVYWENNA",
  DA_PAN = "DA_PAN",
  POGRANICHNIK = "POGRANICHNIK",
  ALESH = "ALESH",
  ARCLIGHT = "ARCLIGHT",
}

export enum EnemyType {
  // ── Aggeloi ─────────────────────────────────────────────────────────────────
  RAM = "RAM",
  RAM_ALPHA = "RAM_ALPHA",
  STING = "STING",
  STING_ALPHA = "STING_ALPHA",
  FALSEWINGS = "FALSEWINGS",
  FALSEWINGS_ALPHA = "FALSEWINGS_ALPHA",
  MUDFLOW = "MUDFLOW",
  MUDFLOW_DELTA = "MUDFLOW_DELTA",
  HEDRON = "HEDRON",
  HEDRON_DELTA = "HEDRON_DELTA",
  PRISM = "PRISM",
  HEAVY_RAM = "HEAVY_RAM",
  HEAVY_RAM_ALPHA = "HEAVY_RAM_ALPHA",
  HEAVY_STING = "HEAVY_STING",
  HEAVY_STING_ALPHA = "HEAVY_STING_ALPHA",
  EFFIGY = "EFFIGY",
  SENTINEL = "SENTINEL",
  TIDEWALKER = "TIDEWALKER",
  TIDEWALKER_DELTA = "TIDEWALKER_DELTA",
  WALKING_CHRYSOPOLIS = "WALKING_CHRYSOPOLIS",
  TIDALKLAST = "TIDALKLAST",
  TRIAGGELOS = "TRIAGGELOS",
  MARBLE_AGGELOMOIRAI_PALECORE = "MARBLE_AGGELOMOIRAI_PALECORE",
  MARBLE_AGGELOMOIRAI_PALESENT = "MARBLE_AGGELOMOIRAI_PALESENT",
  MARBLE_APPENDAGE = "MARBLE_APPENDAGE",
  // ── Landbreakers ────────────────────────────────────────────────────────────
  BONEKRUSHER_RIPPTUSK = "BONEKRUSHER_RIPPTUSK",
  ELITE_RIPPTUSK = "ELITE_RIPPTUSK",
  HAZEFYRE_TUSKBEAST = "HAZEFYRE_TUSKBEAST",
  HAZEFYRE_CLAW = "HAZEFYRE_CLAW",
  BONEKRUSHER_RAIDER = "BONEKRUSHER_RAIDER",
  ELITE_RAIDER = "ELITE_RAIDER",
  BONEKRUSHER_AMBUSHER = "BONEKRUSHER_AMBUSHER",
  ELITE_AMBUSHER = "ELITE_AMBUSHER",
  BONEKRUSHER_INFILTRATOR = "BONEKRUSHER_INFILTRATOR",
  BONEKRUSHER_VANGUARD = "BONEKRUSHER_VANGUARD",
  BONEKRUSHER_PYROMANCER = "BONEKRUSHER_PYROMANCER",
  BONEKRUSHER_ARSONIST = "BONEKRUSHER_ARSONIST",
  BONEKRUSHER_BALLISTA = "BONEKRUSHER_BALLISTA",
  BONEKRUSHER_EXECUTIONER = "BONEKRUSHER_EXECUTIONER",
  ELITE_EXECUTIONER = "ELITE_EXECUTIONER",
  BONEKRUSHER_SIEGEKNUCKLES = "BONEKRUSHER_SIEGEKNUCKLES",
  RHODAGN_THE_BONEKRUSHING_FIST = "RHODAGN_THE_BONEKRUSHING_FIST",
  // ── Wildlife ────────────────────────────────────────────────────────────────
  ACID_ORIGINIUM_SLUG = "ACID_ORIGINIUM_SLUG",
  BLAZEMIST_ORIGINIUM_SLUG = "BLAZEMIST_ORIGINIUM_SLUG",
  FIREMIST_ORIGINIUM_SLUG = "FIREMIST_ORIGINIUM_SLUG",
  BRUTAL_PINCERBEAST = "BRUTAL_PINCERBEAST",
  INDIGENOUS_PINCERBEAST = "INDIGENOUS_PINCERBEAST",
  WATERLAMP = "WATERLAMP",
  IMBUED_QUILLBEAST = "IMBUED_QUILLBEAST",
  QUILLBEAST = "QUILLBEAST",
  TUNNELING_NIDWYRM = "TUNNELING_NIDWYRM",
  AXE_ARMORBEAST = "AXE_ARMORBEAST",
  HAZEFYRE_AXE_ARMORBEAST = "HAZEFYRE_AXE_ARMORBEAST",
  GLARING_RAKERBEAST = "GLARING_RAKERBEAST",
  SPOTTED_RAKERBEAST = "SPOTTED_RAKERBEAST",
  // ── Cangzei Pirates ─────────────────────────────────────────────────────────
  GROVE_ARCHER = "GROVE_ARCHER",
  ROAD_PLUNDERER = "ROAD_PLUNDERER",
}

export enum EnemyTierType {
  COMMON = "COMMON",
  ADVANCED = "ADVANCED",
  ELITE = "ELITE",
  ALPHA = "ALPHA",
  BOSS = "BOSS",
}

export enum RaceType {
  LANDBREAKERS = "LANDBREAKERS",
  AGGELOI = "AGGELOI",
  CANGZEI_PIRATES = "CANGZEI_PIRATES",
  WILDLIFE = "WILDLIFE",
}

export enum EnemyLocationType {
  GROUND = "GROUND",
  AIRBORNE = "AIRBORNE",
}

export enum EnemyStatType {
  HP = "HP",
  ATK = "ATK",
  DEF = "DEF",
  PHYSICAL_RESISTANCE = "PHYSICAL_RESISTANCE",
  HEAT_RESISTANCE = "HEAT_RESISTANCE",
  ELECTRIC_RESISTANCE = "ELECTRIC_RESISTANCE",
  CRYO_RESISTANCE = "CRYO_RESISTANCE",
  NATURE_RESISTANCE = "NATURE_RESISTANCE",
  AETHER_RESISTANCE = "AETHER_RESISTANCE",
  STAGGER_HP = "STAGGER_HP",
  STAGGER_RECOVERY = "STAGGER_RECOVERY",
  FINISHER_ATK_MULTIPLIER = "FINISHER_ATK_MULTIPLIER",
  FINISHER_SP_GAIN = "FINISHER_SP_GAIN",
  ATTACK_RANGE = "ATTACK_RANGE",
  WEIGHT = "WEIGHT",
}

export enum WeaponSkillType {
  // ── Stat boosts (each has _S / _M / _L size variants) ──────────────────────
  ATTACK_BOOST_S = "ATTACK_BOOST_S",
  ATTACK_BOOST_M = "ATTACK_BOOST_M",
  ATTACK_BOOST_L = "ATTACK_BOOST_L",

  STRENGTH_BOOST_S = "STRENGTH_BOOST_S",
  STRENGTH_BOOST_M = "STRENGTH_BOOST_M",
  STRENGTH_BOOST_L = "STRENGTH_BOOST_L",

  AGILITY_BOOST_S = "AGILITY_BOOST_S",
  AGILITY_BOOST_M = "AGILITY_BOOST_M",
  AGILITY_BOOST_L = "AGILITY_BOOST_L",

  INTELLECT_BOOST_S = "INTELLECT_BOOST_S",
  INTELLECT_BOOST_M = "INTELLECT_BOOST_M",
  INTELLECT_BOOST_L = "INTELLECT_BOOST_L",

  WILL_BOOST_S = "WILL_BOOST_S",
  WILL_BOOST_M = "WILL_BOOST_M",
  WILL_BOOST_L = "WILL_BOOST_L",

  MAIN_ATTRIBUTE_BOOST_S = "MAIN_ATTRIBUTE_BOOST_S",
  MAIN_ATTRIBUTE_BOOST_M = "MAIN_ATTRIBUTE_BOOST_M",
  MAIN_ATTRIBUTE_BOOST_L = "MAIN_ATTRIBUTE_BOOST_L",

  PHYSICAL_DAMAGE_BOOST_S = "PHYSICAL_DAMAGE_BOOST_S",
  PHYSICAL_DAMAGE_BOOST_M = "PHYSICAL_DAMAGE_BOOST_M",
  PHYSICAL_DAMAGE_BOOST_L = "PHYSICAL_DAMAGE_BOOST_L",

  HEAT_DAMAGE_BOOST_S = "HEAT_DAMAGE_BOOST_S",
  HEAT_DAMAGE_BOOST_M = "HEAT_DAMAGE_BOOST_M",
  HEAT_DAMAGE_BOOST_L = "HEAT_DAMAGE_BOOST_L",

  CRYO_DAMAGE_BOOST_S = "CRYO_DAMAGE_BOOST_S",
  CRYO_DAMAGE_BOOST_M = "CRYO_DAMAGE_BOOST_M",
  CRYO_DAMAGE_BOOST_L = "CRYO_DAMAGE_BOOST_L",

  NATURE_DAMAGE_BOOST_S = "NATURE_DAMAGE_BOOST_S",
  NATURE_DAMAGE_BOOST_M = "NATURE_DAMAGE_BOOST_M",
  NATURE_DAMAGE_BOOST_L = "NATURE_DAMAGE_BOOST_L",

  ELECTRIC_DAMAGE_BOOST_S = "ELECTRIC_DAMAGE_BOOST_S",
  ELECTRIC_DAMAGE_BOOST_M = "ELECTRIC_DAMAGE_BOOST_M",
  ELECTRIC_DAMAGE_BOOST_L = "ELECTRIC_DAMAGE_BOOST_L",

  ULTIMATE_GAIN_EFFICIENCY_BOOST_S = "ULTIMATE_GAIN_EFFICIENCY_BOOST_S",
  ULTIMATE_GAIN_EFFICIENCY_BOOST_M = "ULTIMATE_GAIN_EFFICIENCY_BOOST_M",
  ULTIMATE_GAIN_EFFICIENCY_BOOST_L = "ULTIMATE_GAIN_EFFICIENCY_BOOST_L",

  HP_BOOST_S = "HP_BOOST_S",
  HP_BOOST_M = "HP_BOOST_M",
  HP_BOOST_L = "HP_BOOST_L",

  ARTS_BOOST_S = "ARTS_BOOST_S",
  ARTS_BOOST_M = "ARTS_BOOST_M",
  ARTS_BOOST_L = "ARTS_BOOST_L",

  ARTS_INTENSITY_BOOST_S = "ARTS_INTENSITY_BOOST_S",
  ARTS_INTENSITY_BOOST_M = "ARTS_INTENSITY_BOOST_M",
  ARTS_INTENSITY_BOOST_L = "ARTS_INTENSITY_BOOST_L",

  CRITICAL_RATE_BOOST_S = "CRITICAL_RATE_BOOST_S",
  CRITICAL_RATE_BOOST_M = "CRITICAL_RATE_BOOST_M",
  CRITICAL_RATE_BOOST_L = "CRITICAL_RATE_BOOST_L",

  TREATMENT_EFFICIENCY_BOOST_S = "TREATMENT_EFFICIENCY_BOOST_S",
  TREATMENT_EFFICIENCY_BOOST_M = "TREATMENT_EFFICIENCY_BOOST_M",
  TREATMENT_EFFICIENCY_BOOST_L = "TREATMENT_EFFICIENCY_BOOST_L",

  // ── Named weapon skills ─────────────────────────────────────────────────────
  BRUTALITY_DISCIPLINARIAN = "BRUTALITY_DISCIPLINARIAN",
  TWILIGHT_BLAZING_WAIL = "TWILIGHT_BLAZING_WAIL",
  TWILIGHT_AZURE_CLOUDS = "TWILIGHT_AZURE_CLOUDS",
  INFLICTION_WHITE_NIGHT_NOVA = "INFLICTION_WHITE_NIGHT_NOVA",
  FLOW_REINCARNATION = "FLOW_REINCARNATION",
  INFLICTION_LONG_TIME_WISH = "INFLICTION_LONG_TIME_WISH",
  FLOW_THERMAL_RELEASE = "FLOW_THERMAL_RELEASE",
  INFLICTION_COVETOUS_BUILDUP = "INFLICTION_COVETOUS_BUILDUP",
  COMBATIVE_ANTHEM_OF_CINDER = "COMBATIVE_ANTHEM_OF_CINDER",
  INSPIRING_BACK_TO_THE_BROKEN_CITY = "INSPIRING_BACK_TO_THE_BROKEN_CITY",
  TWILIGHT_IMPOSING_PEAK = "TWILIGHT_IMPOSING_PEAK",
  FLOW_UNBRIDLED_EDGE = "FLOW_UNBRIDLED_EDGE",
  INFLICTION_SINCERE_INTERROGATION = "INFLICTION_SINCERE_INTERROGATION",
  SUPPRESSION_FIN_CHASERS_INTENT = "SUPPRESSION_FIN_CHASERS_INTENT",
  PURSUIT_UNENDING_CYCLE = "PURSUIT_UNENDING_CYCLE",
  SUPPRESSION_EMERGENCY_BOOST = "SUPPRESSION_EMERGENCY_BOOST",
  ASSAULT_ARMAMENT_PREP = "ASSAULT_ARMAMENT_PREP",
  TWILIGHT_LUSTROUS_PYRE = "TWILIGHT_LUSTROUS_PYRE",
  INFLICTION_VICIOUS_PURGE = "INFLICTION_VICIOUS_PURGE",
  INFLICTION_TIDAL_MURMURS = "INFLICTION_TIDAL_MURMURS",

  // ── Additional named weapon skills ────────────────────────────────────────
  CRUSHER_PRINCELY_DETERRENCE = "CRUSHER_PRINCELY_DETERRENCE",
  CRUSHER_HONED_INTO_LEGION = "CRUSHER_HONED_INTO_LEGION",
  SUPPRESSION_STACKED_HEW = "SUPPRESSION_STACKED_HEW",
  SUPPRESSION_ASTROPHYSICS = "SUPPRESSION_ASTROPHYSICS",
  SUPPRESSION_CONCENTRIC_CIRCLES = "SUPPRESSION_CONCENTRIC_CIRCLES",
  COMBATIVE_VIRTUOUS_GAIN = "COMBATIVE_VIRTUOUS_GAIN",
  BRUTALITY_CEMENTED_FURY = "BRUTALITY_CEMENTED_FURY",
  BRUTALITY_LANDS_OF_YORE = "BRUTALITY_LANDS_OF_YORE",
  DETONATE_BONECHILLING = "DETONATE_BONECHILLING",
  DETONATE_SEEKER_OF_THE_ESOTERIC = "DETONATE_SEEKER_OF_THE_ESOTERIC",
  DETONATE_IMPOSING_CHAMPION = "DETONATE_IMPOSING_CHAMPION",
  EFFICACY_TENACIOUS_WILL = "EFFICACY_TENACIOUS_WILL",
  FRACTURE_ARTZY_EXAGGERATION = "FRACTURE_ARTZY_EXAGGERATION",
  PURSUIT_AID_FROM_THE_PAST = "PURSUIT_AID_FROM_THE_PAST",
  PURSUIT_DUTY_FULFILLED = "PURSUIT_DUTY_FULFILLED",
  PURSUIT_TRANSCENDENT_ARTS = "PURSUIT_TRANSCENDENT_ARTS",
  INFLICTION_ROAD_HOME_FOR_ALL_LIFE = "INFLICTION_ROAD_HOME_FOR_ALL_LIFE",
  INFLICTION_WILDERNESS_CLUSTER = "INFLICTION_WILDERNESS_CLUSTER",
  INFLICTION_WEDGE_OF_CIVILIZATION = "INFLICTION_WEDGE_OF_CIVILIZATION",
  INFLICTION_CONQUEST_OF_ICY_PEAKS = "INFLICTION_CONQUEST_OF_ICY_PEAKS",
  TWILIGHT_HUMILIATION = "TWILIGHT_HUMILIATION",
  MEDICANT_BLIGHT_FERVOR = "MEDICANT_BLIGHT_FERVOR",
  MEDICANT_EYE_OF_TALOS = "MEDICANT_EYE_OF_TALOS",
  MEDICANT_REDEMPTION_OF_FAITH = "MEDICANT_REDEMPTION_OF_FAITH",
  MINCING_THERAPY = "MINCING_THERAPY",
  MEDICANT_GLORY_OF_KNIGHTHOOD = "MEDICANT_GLORY_OF_KNIGHTHOOD",
  WEIGHT_OF_MOUNTAIN = "WEIGHT_OF_MOUNTAIN",
  INSPIRING_START_OF_A_SAGA = "INSPIRING_START_OF_A_SAGA",
  INFLICTION_LONE_AND_DISTANT_SAIL = "INFLICTION_LONE_AND_DISTANT_SAIL",
  DETONATE_RAPID_STRIKE = "DETONATE_RAPID_STRIKE",
  SUPPRESSION_TILLITE_ETCHINGS = "SUPPRESSION_TILLITE_ETCHINGS",
  INSPIRING_MORTISE_AND_TENON_ANALYSIS = "INSPIRING_MORTISE_AND_TENON_ANALYSIS",
}
