import { StatType } from "./enums";

/** Fraction of natural SP consumed that converts to team-wide ultimate charge. */
export const NATURAL_SP_TO_ULTIMATE_RATIO = 0.065;

/** Default baseline for all stats (attributes and combat stats). */
export const DEFAULT_STATS: Readonly<Record<StatType, number>> = {
  [StatType.BASE_HP]: 0,
  [StatType.BASE_DEFENSE]: 0,
  [StatType.BASE_ATTACK]: 0,
  [StatType.ATTACK_BONUS]: 0,
  [StatType.STRENGTH]: 0,
  [StatType.STRENGTH_BONUS]: 0,
  [StatType.AGILITY]: 0,
  [StatType.AGILITY_BONUS]: 0,
  [StatType.INTELLECT]: 0,
  [StatType.INTELLECT_BONUS]: 0,
  [StatType.WILL]: 0,
  [StatType.WILL_BONUS]: 0,
  [StatType.CRITICAL_RATE]: 0,
  [StatType.CRITICAL_DAMAGE]: 0,
  [StatType.ARTS_INTENSITY]: 0,
  [StatType.PHYSICAL_RESISTANCE]: 0,
  [StatType.HEAT_RESISTANCE]: 0,
  [StatType.ELECTRIC_RESISTANCE]: 0,
  [StatType.CRYO_RESISTANCE]: 0,
  [StatType.NATURE_RESISTANCE]: 0,
  [StatType.AETHER_RESISTANCE]: 0,
  [StatType.TREATMENT_BONUS]: 0,
  [StatType.TREATMENT_RECEIVED_BONUS]: 0,
  [StatType.COMBO_SKILL_COOLDOWN_REDUCTION]: 0,
  [StatType.ULTIMATE_GAIN_EFFICIENCY]: 0,
  [StatType.STAGGER_EFFICIENCY_BONUS]: 0,
  [StatType.PHYSICAL_DAMAGE_BONUS]: 0,
  [StatType.HEAT_DAMAGE_BONUS]: 0,
  [StatType.ELECTRIC_DAMAGE_BONUS]: 0,
  [StatType.CRYO_DAMAGE_BONUS]: 0,
  [StatType.NATURE_DAMAGE_BONUS]: 0,
  [StatType.BASIC_ATTACK_DAMAGE_BONUS]: 0,
  [StatType.BATTLE_SKILL_DAMAGE_BONUS]: 0,
  [StatType.COMBO_SKILL_DAMAGE_BONUS]: 0,
  [StatType.ULTIMATE_DAMAGE_BONUS]: 0,
  [StatType.STAGGER_DAMAGE_BONUS]: 0,
  [StatType.FINAL_DAMAGE_REDUCTION]: 0,
  [StatType.SKILL_DAMAGE_BONUS]: 0,
  [StatType.ARTS_DAMAGE_BONUS]: 0,
  [StatType.HP_BONUS]: 0,
  [StatType.FLAT_HP]: 0,
  // ── Enemy stats ──────────────────────────────────────────────────────────────
  [StatType.STAGGER_HP]: 0,
  [StatType.STAGGER_RECOVERY]: 0,
  [StatType.FINISHER_ATK_MULTIPLIER]: 0,
  [StatType.FINISHER_SP_GAIN]: 0,
  [StatType.ATTACK_RANGE]: 0,
  [StatType.WEIGHT]: 0,
};
